Repository matecat/MateCat, pull requests merged in 2021-05, with the labels that each got.

#1994 ✅ first manage page render test
  .eslintrc.js
  package.json
  public/js/analyze.test.js
  public/js/cat_source/es6/ajax_utils/jobAjax.js
  public/js/cat_source/es6/components/analyze/AnalyzeChunksResume.js
  public/js/cat_source/es6/components/analyze/AnalyzeHeader.js
  public/js/cat_source/es6/components/analyze/AnalyzeMain.js
  public/js/cat_source/es6/components/analyze/ChunkAnalyze.js
  public/js/cat_source/es6/components/analyze/ChunkAnalyzeFile.js
  public/js/cat_source/es6/components/analyze/ChunkAnalyzeHeader.js
  public/js/cat_source/es6/components/analyze/JobAnalyze.js
  public/js/cat_source/es6/components/analyze/JobAnalyzeHeader.js
  public/js/cat_source/es6/components/analyze/JobTableHeader.js
  public/js/cat_source/es6/components/analyze/ProjectAnalyze.js
  public/js/cat_source/es6/components/header/ActionMenu.js
  public/js/cat_source/es6/components/header/HeaderProjectInfo.js
  public/js/cat_source/es6/components/header/TeamsSelect.js
  public/js/cat_source/es6/components/header/manage/FilterProjects.js
  public/js/cat_source/es6/components/header/manage/FilterProjectsStatus.js
  public/js/cat_source/es6/components/header/manage/SearchInput.js
  public/js/cat_source/es6/components/modals/ModalContainerComponent.js
  public/js/cat_source/es6/components/modals/ModalOverlayComponent.js
  public/js/cat_source/es6/components/modals/ModalWindowComponent.js
  public/js/cat_source/es6/components/outsource/AssignToTranslator.js
  public/js/cat_source/es6/components/outsource/GMTSelect.js
  public/js/cat_source/es6/components/outsource/OpenJobBox.js
  public/js/cat_source/es6/components/outsource/OutsourceContainer.js
  public/js/cat_source/es6/components/outsource/OutsourceInfo.js
  public/js/cat_source/es6/components/outsource/OutsourceVendor.js
  public/js/cat_source/es6/utils/textUtils.js
  public/js/lib/diff_match_patch.js
  public/js/manage.js
  public/js/manage.test.js
  public/js/user_store.js
  setupFiles.jest.js
  yarn.lock
Labels: Freddy

#2003 [h1-6] check removed
  lib/Utils/SubFiltering/Filters/HtmlToPh.php
Labels: Ready for prod

#2002 Develop xliff pc tags
  composer.lock
  test/unit/Subfiltering/SubFilteringTest.php
Labels: Ready for prod

#2000 Remove html and markdown support in segment notes
  public/js/cat_source/es6/components/segments/SegmentFooterTabMessages.js
Labels: Ready for prod

#1999 Cambio lingua da Chinese Macau a Chinese Traditional Macau
  lib/Utils/Langs/supported_langs.json
Labels: Ready for prod

#1998 API: Limited Max upload files from config
  lib/Utils/API/Upload.php
Labels: Ready for prod

#1997 Fix: return context-groups in getSegments api
  lib/Model/Segments/ContextStruct.php
  lib/Model/Segments/SegmentUIStruct.php
Labels: Ready for prod

#1985 Update nodejs
  .travis.yml
  nodejs/config.ini.sample
  nodejs/package-lock.json
  nodejs/package.json
  nodejs/server.js
  support_scripts/grunt/package-lock.json
  support_scripts/grunt/package.json
Labels: In Progress

#2012 Move and merge package.json and Gruntfile
  .gitignore
  .travis.yml
  Gruntfile.js
  package-lock.json
  package.json
  public/js/cat_source/es6/components/modals/DQFCredentials.js
  public/js/cat_source/es6/components/modals/ForgotPasswordModal.js
  public/js/cat_source/es6/components/modals/LoginModal.js
  public/js/cat_source/es6/components/modals/RegisterModal.js
  public/js/cat_source/es6/components/modals/ResetPasswordModal.js
  public/js/lib/lokijs.min.js
  support_scripts/grunt/.gitignore
  support_scripts/grunt/.npmrc
  support_scripts/grunt/package-lock.json
  support_scripts/grunt/package.json
  support_scripts/husky/.gitignore
  support_scripts/husky/pre-commit
  yarn.lock
Labels: In Progress

#2015 Strip tags from notes before persisting on DB
  lib/Model/ProjectManager/ProjectManagerModel.php
Labels: Ready for prod

#2014 translation replacement + handling of `<ec>` and `<sc>` tags
  composer.lock
  lib/Utils/SubFiltering/Filters/PlaceHoldXliffTags.php
  nodejs/package-lock.json
Labels: Ready for prod

#2010 Fixed step parameter and ghost segments
  lib/Model/QualityReport/QualityReportSegmentModel.php
  lib/Model/Segments/SegmentDao.php
  lib/Plugins/Features/ReviewExtended/Controller/API/QualityReportController.php
Labels: Ready for prod

#2021 Fixed QA API v3 segment ordering
  lib/Model/QualityReport/QualityReportSegmentModel.php
Labels: Ready for prod

#2023 Context-group: hide if structure not respect specifications
  public/js/cat_source/es6/components/segments/SegmentFooterTabMessages.js
Labels: Ready for prod

#2030 Develop ph analysis filter ref
  lib/Controller/API/V2/ChunkTranslationVersionController.php
  lib/Controller/API/V2/ReviseTranslationIssuesController.php
  lib/Controller/API/V2/SegmentVersion.php
  lib/Controller/deleteContributionController.php
  lib/Controller/downloadFileController.php
  lib/Controller/getContributionController.php
  lib/Controller/getSearchController.php
  lib/Controller/getSegmentsController.php
  lib/Controller/getTagProjectionController.php
  lib/Controller/getWarningController.php
  lib/Controller/glossaryController.php
  lib/Controller/setCurrentSegmentController.php
  lib/Controller/setRevisionController.php
  lib/Controller/setSegmentSplitController.php
  lib/Controller/setTranslationController.php
  lib/Model/EditLog/EditLogModel.php
  lib/Model/GlossaryModel.php
  lib/Model/Jobs/JobDao.php
  lib/Model/QualityReport/QualityReportSegmentModel.php
  lib/Model/Segments/SegmentDao.php
  lib/Utils/Analysis/Workers/TMAnalysisWorker.php
  lib/Utils/AsyncTasks/Workers/GetContributionWorker.php
  lib/Utils/Engines/Results/MyMemory/Matches.php
  lib/Utils/Engines/Results/MyMemory/TMS.php
  lib/Utils/ProjectManager.php
  lib/Utils/SubFiltering/Filter.php
  lib/Utils/SubFiltering/Filters/Sprintf/SprintfLocker.php
  lib/Utils/SubFiltering/Filters/Sprintf/language/all/not_allowed.php
  lib/Utils/SubFiltering/Filters/Sprintf/language/az-AZ/not_allowed.php
  lib/Utils/SubFiltering/Filters/Sprintf/language/de-AT/not_allowed.php
  lib/Utils/SubFiltering/Filters/Sprintf/language/de-CH/not_allowed.php
  lib/Utils/SubFiltering/Filters/Sprintf/language/de-DE/not_allowed.php
  lib/Utils/SubFiltering/Filters/Sprintf/language/hu-HU/not_allowed.php
  lib/Utils/SubFiltering/Filters/SprintfToPH.php
  lib/Utils/TMSService.php
  lib/Utils/XliffReplacer/XliffReplacerCallback.php
  lib/View/API/V2/Json/QALocalWarning.php
  lib/View/API/V2/Json/SegmentTranslationMismatches.php
  lib/View/API/V2/Json/SegmentVersion.php
  test/Tests/QATest.php
  test/unit/Model/SearchModelTest.php
  test/unit/PostProcessTest.php
  test/unit/Subfiltering/SubFilteringTest.php
  test/unit/TagPositionTest.php
  test/unit/TestCatUtils/RawXliff2ViewTest.php
  test/unit/TestCatUtils/RestorexlifftagsforviewTest.php
  test/unit/TestCatUtils/View2rawxliffTest.php
  test/unit/TestContribution/SetContributionWorkerTest.php
Labels: Ready for prod

#2031 Fix chromebook
  public/js/cat_source/es6/components/segments/Editarea.js
Labels: Freddy

#2033 Fixed wrong query in segment dao ( unknown table )
  inc/version.ini
  lib/Model/Segments/SegmentDao.php
Labels: Ready for prod

#2035 Egyptian arabic
  lib/Utils/Langs/supported_langs.json
Labels: Ready for prod

#1987 Glossary async reload
  lib/Controller/glossaryController.php
  lib/Utils/AsyncTasks/Workers/GetContributionWorker.php
  lib/Utils/AsyncTasks/Workers/GlossaryWorker.php
  lib/Utils/Engines/MyMemory.php
  lib/Utils/TmKeyManagement/TmKeyManagement.php
  nodejs/package-lock.json
  nodejs/server.js
  public/js/cat_source/es6/actions/CatToolActions.js
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/ajax_utils/segmentAjax.js
  public/js/cat_source/es6/components/segments/Segment.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabGlossary.js
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/activateGlossary.js
  public/js/cat_source/es6/constants/CatToolConstants.js
  public/js/cat_source/es6/constants/SegmentConstants.js
  public/js/cat_source/es6/sse/sse.js
  public/js/cat_source/es6/stores/CatToolStore.js
  public/js/cat_source/es6/stores/SegmentStore.js
Labels: Ready for prod
