Repository matecat/MateCat, pull requests merged in 2021-06, with the labels that each got.

#2046 [API][Create project] Trim private_tm_key
  lib/Controller/API/NewController.php
Labels: Freddy, Ready for prod

#2045 Fix replaceAll with strings with a slash
  composer.lock
Labels: Freddy, Ready for prod

#2053 Analysis page: Hide industry industry weighted
  public/css/sass/commons/_analyze.scss
  public/js/cat_source/es6/components/analyze/AnalyzeChunksResume.js
Labels: Ready for prod

#2054 Fix whole text search
  lib/Controller/getSearchController.php
Labels: Ready for prod

#2038 Xliff parser 1.0.64 + Subfiltering test fixing
  nodejs/package-lock.json
  public/js/cat_source/es6/components/modals/RevisionFeedbackModal.js
  public/js/cat_source/es6/stores/CatToolStore.js
  test/unit/Subfiltering/SubFilteringTest.php
Labels: Freddy, Ready for prod

#2055 Revert analysis page changes
  public/css/sass/commons/_analyze.scss
  public/js/cat_source/es6/components/analyze/AnalyzeChunksResume.js
Labels: Ready for prod

#2058 Protect signup form
  lib/Model/Users/Signup.php
Labels: Freddy, Ready for prod

#2057 CJK - stop adding trailing space to target
  lib/Utils/QA.php
Labels: Freddy, Ready for prod

#2063 Remove react.js script
  Gruntfile.js
  lib/View/activity_log.html
  lib/View/analyze.html
  lib/View/editlog.html
  lib/View/index.html
  lib/View/jobAnalysis.html
  lib/View/manage.html
  lib/View/pee.html
  lib/View/revise_summary.html
  lib/View/revise_summary_old.html
  lib/View/upload.html
  lib/View/xliffToTarget.html
  public/js/cat_source/es6/react-libs.js
Labels: In Progress

#2064 Added Tamil India to supported languages
  lib/Utils/Langs/supported_langs.json
Labels: Ready for prod

#2065 Fix download zipped xliff (in intermediate xlf)
  lib/Controller/downloadFileController.php
Labels: Freddy

#2039 Refactoring/manage
  Gruntfile.js
  lib/View/manage.html
  public/js/cat_source/es6/actions/ManageActions.js
  public/js/cat_source/es6/actions/TeamsActions.js
  public/js/cat_source/es6/ajax_utils/projectsAjax.js
  public/js/cat_source/es6/components.js
  public/js/cat_source/es6/components/header/Header.js
  public/js/cat_source/es6/components/header/TeamsSelect.js
  public/js/cat_source/es6/components/header/manage/FilterProjects.js
  public/js/cat_source/es6/components/modals/CreateTeam.js
  public/js/cat_source/es6/components/modals/ModifyTeam.js
  public/js/cat_source/es6/components/projects/Dashboard.js
  public/js/cat_source/es6/components/projects/Dashboard.test.js
  public/js/cat_source/es6/components/projects/Header.js
  public/js/cat_source/es6/components/projects/JobContainer.js
  public/js/cat_source/es6/components/projects/JobMenu.js
  public/js/cat_source/es6/components/projects/ProjectContainer.js
  public/js/cat_source/es6/components/projects/ProjectsContainer.js
  public/js/cat_source/es6/constants/ManageConstants.js
  public/js/cat_source/es6/stores/ProjectsStore.js
  public/js/cat_source/es6/stores/TeamsStore.js
  public/js/common.js
  public/js/manage.js
  public/js/outsource.js
Labels: Ready for prod

#2069 New subfiltering
  composer.lock
Labels: Ready for prod

#2072 GuessTag fix
  composer.lock
  lib/Controller/getTagProjectionController.php
  lib/Utils/Engines/MyMemory.php
  lib/Utils/Engines/Results/AbstractResponse.php
  lib/Utils/Engines/Results/MyMemory/TagProjectionResponse.php
Labels: Freddy, Ready for prod
