Repository matecat/MateCat, pull requests merged in 2021-11, with the labels that each got.

#2227 Segment characters counter
  composer.lock
  inc/version.ini
  lib/Controller/getWarningController.php
  lib/Controller/setTranslationController.php
  lib/Model/Segments/SegmentMetadataDao.php
  lib/Utils/ProjectManager.php
  lib/Utils/QA.php
  lib/Utils/XliffReplacer/XliffReplacerCallback.php
  lib/View/API/V2/Json/QALocalWarning.php
  lib/View/API/V2/Json/QAWarning.php
  public/css/sass/commons/_buttons.scss
  public/css/sass/components/segment/segment.scss
  public/css/sass/speech2text.scss
  public/css/sass/style.scss
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/components/segments/Editarea.js
  public/js/cat_source/es6/components/segments/SegmentTarget.js
  public/js/cat_source/es6/constants/SegmentConstants.js
  public/js/cat_source/es6/stores/SegmentStore.js
Labels: Ready for prod, Freddy

#2233 Cache on getByChunkIdAndSegmentId
  lib/Model/Segments/SegmentDao.php
Labels: enhancement, Ready for prod

#2234 Develop api for downloading QR
  lib/Controller/API/V3/DownloadQRController.php
  lib/Model/DownloadQR/DownloadQRModel.php
  lib/Routes/api_v3_routes.php
Labels: Ready for prod, Freddy

#2230 Updated to subfiltering v1.0.14
  composer.lock
Labels: Ready for prod, Freddy

#2241 Supported subjects
  lib/Utils/Langs/languageDomains.json
Labels: Ready for prod, Freddy

#2239 Fix dialog size supported formats
  public/css/sass/upload-page.scss
Labels: Freddy

#2231 TM api from doRequest to fetch
  public/js/cat_source/es6/api/addMTEngine/addMTEngine.js
  public/js/cat_source/es6/api/addMTEngine/index.js
  public/js/cat_source/es6/api/checkTMKey/checkTMKey.js
  public/js/cat_source/es6/api/checkTMKey/index.js
  public/js/cat_source/es6/api/createNewTmKey/createNewTmKey.js
  public/js/cat_source/es6/api/createNewTmKey/index.js
  public/js/cat_source/es6/api/deleteMTEngine/deleteMTEngine.js
  public/js/cat_source/es6/api/deleteMTEngine/index.js
  public/js/cat_source/es6/api/deleteTmKey/deleteTmKey.js
  public/js/cat_source/es6/api/deleteTmKey/index.js
  public/js/cat_source/es6/api/downloadTMX/downloadTMX.js
  public/js/cat_source/es6/api/downloadTMX/index.js
  public/js/cat_source/es6/api/getInfoTmKey/getInfoTmKey.js
  public/js/cat_source/es6/api/getInfoTmKey/index.js
  public/js/cat_source/es6/api/loadGlossaryFile/index.js
  public/js/cat_source/es6/api/loadGlossaryFile/loadGlossaryFile.js
  public/js/cat_source/es6/api/loadTMX/index.js
  public/js/cat_source/es6/api/loadTMX/loadTMX.js
  public/js/cat_source/es6/api/shareTmKey/index.js
  public/js/cat_source/es6/api/shareTmKey/shareTmKey.js
  public/js/cat_source/es6/api/tmCreateRandUser/index.js
  public/js/cat_source/es6/api/tmCreateRandUser/tmCreateRandUser.js
  public/js/cat_source/es6/api/updateJobKeys/index.js
  public/js/cat_source/es6/api/updateJobKeys/updateJobKeys.js
  public/js/cat_source/es6/api/updateTmKey/index.js
  public/js/cat_source/es6/api/updateTmKey/updateTmKey.js
  public/js/tm.js
Labels: Freddy

#2236 Quality report page download CSV file
  public/css/sass/style.scss
  public/js/cat_source/es6/api/exportQualityReport/exportQualityReport.js
  public/js/cat_source/es6/api/exportQualityReport/index.js
  public/js/cat_source/es6/components/header/ActionMenu.js
Labels: Ready for prod

#2242 [download QR] Added three more issue counters + download unique file
  lib/Controller/API/V3/DownloadQRController.php
Labels: Ready for prod

#2244 Refactoring App doRequest part 3
  public/js/cat_source/es6/actions/CommentsActions.js
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/api/checkConnectionPing/checkConnectionPing.js
  public/js/cat_source/es6/api/checkConnectionPing/index.js
  public/js/cat_source/es6/api/copyAllSourceToTarget/copyAllSourceToTarget.js
  public/js/cat_source/es6/api/copyAllSourceToTarget/index.js
  public/js/cat_source/es6/api/createProject/createProject.js
  public/js/cat_source/es6/api/createProject/index.js
  public/js/cat_source/es6/api/deleteContribution/deleteContribution.js
  public/js/cat_source/es6/api/deleteContribution/index.js
  public/js/cat_source/es6/api/getComments/getComments.js
  public/js/cat_source/es6/api/getComments/index.js
  public/js/cat_source/es6/api/getContributions/getContributions.js
  public/js/cat_source/es6/api/markAsResolvedThread/index.js
  public/js/cat_source/es6/api/markAsResolvedThread/markAsResolvedThread.js
  public/js/cat_source/es6/api/replaceAllIntoSegments/index.js
  public/js/cat_source/es6/api/replaceAllIntoSegments/replaceAllIntoSegments.js
  public/js/cat_source/es6/api/searchTermIntoSegments/index.js
  public/js/cat_source/es6/api/searchTermIntoSegments/searchTermIntoSegments.js
  public/js/cat_source/es6/api/submitComment/index.js
  public/js/cat_source/es6/api/submitComment/submitComment.js
  public/js/cat_source/es6/components/header/cattol/search/Search.js
  public/js/cat_source/es6/components/header/cattol/search/searchUtils.js
  public/js/cat_source/es6/components/segments/SegmentCommentsContainer.js
  public/js/cat_source/es6/components/segments/utils/translationMatches.js
  public/js/cat_source/es6/utils/mbc.main.js
  public/js/cat_source/es6/utils/offlineUtils.js
  public/js/lib/fileupload/main.js
  public/js/new-project.js
Labels: Freddy

#2246 Refactorin APP.doRquest: setTranslation
  public/css/sass/style.scss
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/api/getConcordance/getConcordance.js
  public/js/cat_source/es6/api/getContributions/getContributions.js
  public/js/cat_source/es6/api/setTranslation/setTranslation.js
  public/js/cat_source/es6/components/header/cattol/search/Search.js
  public/js/cat_source/es6/components/review_extended/ReviewExtendedIssuePanel.js
  public/js/cat_source/es6/components/segments/Segment.js
  public/js/cat_source/es6/components/segments/SegmentFooterMultiMatches.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabMatches.js
  public/js/cat_source/es6/components/segments/utils/translationMatches.js
  public/js/cat_source/es6/stores/SegmentStore.js
  public/js/cat_source/ui.core.js
Labels: Freddy

#2251 Experimental: Change Payable Rate to ICE Matches
  lib/Utils/Analysis/Workers/TMAnalysisWorker.php
  public/js/cat_source/es6/components/analyze/JobTableHeader.js
Labels: Freddy

#2250 New unsupported browser page
  inc/INIT.php
  lib/View/unsupported_browser.html
  lib/View/upload.html
  lib/View/xliffToTarget.html
  public/css/sass/common.scss
  public/img/edge.jpg
Labels: Freddy
