Repository matecat/MateCat, pull requests merged in 2021-07, with the labels that each got.

#2085 Lexiqa: Change Tamil language code
  lib/Model/ProjectOptionsSanitizer.php
Labels: Ready for prod

#2083 Manage: fix split on click
  public/js/cat_source/es6/actions/ManageActions.js
  public/js/cat_source/es6/components/projects/JobContainer.js
  public/js/cat_source/es6/components/projects/JobMenu.js
Labels: Ready for prod

#2077 TM search: Add locale to results
  public/js/cat_source/es6/components/segments/SegmentFooterTabConcordance.js
  public/js/cat_source/es6/utils/commonUtils.js
Labels: Ready for prod

#2076 Quality report: change issues button behaviour
  public/js/cat_source/es6/components/quality_report/FileDetails.js
  public/js/cat_source/es6/components/quality_report/QualityReport.js
  public/js/cat_source/es6/components/quality_report/SegmentQR.js
  public/js/cat_source/es6/components/quality_report/SegmentsDetailsContainer.js
Labels: Ready for prod

#2075 Revision panel: add support to severities codes
  public/css/sass/quality-report.scss
  public/js/cat_source/es6/components/review_extended/ReviewExtendedCategorySelector.js
Labels: Ready for prod

#2078 Fix replace all
  lib/Controller/getSearchController.php
  lib/Model/Search/SearchModel.php
Labels: Freddy, Ready for prod

#2080 Refactoring of GetContributionWorker and Engines/Results/MyMemory/TMS
  lib/Utils/AsyncTasks/Workers/GetContributionWorker.php
  lib/Utils/Engines/MyMemory.php
  lib/Utils/Engines/Results/MyMemory/Matches.php
  lib/Utils/Engines/Results/MyMemory/TMS.php
Labels: Ready for prod

#2082 Updated to xliff parser 1.0.67
  composer.lock
Labels: Freddy, Ready for prod

#2086 Comments: Allow comments on splitted jobs
  public/css/sass/mbc-style.scss
  public/js/cat_source/es6/components/segments/Segment.js
  public/js/cat_source/es6/components/segments/SegmentBody.js
  public/js/cat_source/es6/components/segments/SegmentsCommentsIcon.js
Labels: Ready for prod

#2087 Analysis page: fix show details bar position
  public/css/sass/commons/_analyze.scss
Labels: Ready for prod

#2088 Updated to subfiltering v1.0.9
  composer.lock
Labels: Ready for prod

#2093 Fix: job analysis for splitted jobs
  public/js/cat_source/es6/components/analyze/AnalyzeChunksResume.js
Labels: Ready for prod

#2095 Gruntfile: move manage concat to browserify
  Gruntfile.js
  lib/View/manage.html
  public/js/outsource.js
Labels: Ready for prod

#2096 Move analyze concat to browserify
  Gruntfile.js
Labels: Ready for prod

#2098 Move common concat to browserify
  Gruntfile.js
  public/js/common.js
Labels: Ready for prod

#2108 Updated to Xliff parser 1.0.70
  composer.lock
Labels: Ready for prod

#2105 Trailing space: removed korean
  lib/Utils/CatUtils.php
  lib/Utils/QA.php
Labels: Ready for prod

#2102 Fix FastAnalysis
  lib/Utils/Analysis/Workers/FastAnalysis.php
  lib/Utils/Analysis/Workers/TMAnalysisWorker.php
Labels: Ready for prod

#2112 Fix seg brackets
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/createNewEntitiesFromMap.js
Labels: Ready for prod

#2115 Update Node package-lock
  nodejs/package-lock.json
Labels: Ready for prod

#2114 Fix xliff-to-target page
  Gruntfile.js
  lib/View/xliffToTarget.html
Labels: Ready for prod

#2106 Segments Metadata Support
  composer.lock
  lib/Controller/getSegmentsController.php
  lib/Model/Segments/SegmentMetadataDao.php
  lib/Model/Segments/SegmentMetadataStruct.php
  lib/Model/Segments/SegmentUIStruct.php
  lib/Utils/ProjectManager.php
  migrations/20210713175700_create_table_segment_metadata.php
  public/js/cat_source/es6/components/segments/SegmentFooter.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabMessages.js
Labels: Freddy, Ready for prod

#2116 Develop 2digit zip fix
  inc/version.ini
  lib/Controller/AbstractControllers/downloadController.php
  lib/Controller/downloadFileController.php
Labels: Freddy, Ready for prod

#2124 Move js-cookie to npm
  Gruntfile.js
  package.json
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/components/modals/CopySourceModal.js
  public/js/cat_source/es6/components/outsource/AssignToTranslator.js
  public/js/cat_source/es6/components/outsource/GMTSelect.js
  public/js/cat_source/es6/components/outsource/OutsourceContainer.js
  public/js/cat_source/es6/components/outsource/OutsourceVendor.js
  public/js/cat_source/es6/components/projects/JobContainer.test.js
  public/js/cat_source/es6/components/projects/ProjectContainer.test.js
  public/js/cat_source/es6/components/projects/ProjectsContainer.test.js
  public/js/cat_source/es6/components/segments/SegmentFooter.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabConcordance.js
  public/js/cat_source/es6/utils/customizations.js
  public/js/cat_source/ui.core.js
  public/js/common.js
  public/js/lib/fileupload/main.js
  public/js/lib/js.cookie.js
  public/js/new-project.js
  public/js/tm.js
  yarn.lock
Labels: Freddy
