Repository matecat/MateCat, pull requests merged in 2021-12, with the labels that each got.

#2262 Fix charLimit
  lib/Utils/ProjectManager.php
Labels: Ready for prod, Freddy

#2260 Change revision feedback label
  lib/View/tm.html
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/components/modals/RevisionFeedbackModal.js
  public/js/cat_source/es6/components/segments/Segment.js
  public/js/cat_source/es6/components/segments/SegmentHeader.js
  public/js/cat_source/es6/stores/SegmentStore.js
  public/js/new-project.js
Labels: Ready for prod

#2263 Update url regexp
  public/js/cat_source/es6/utils/textUtils.js
Labels: Ready for prod

#2261 Forgot password api parse response
  public/js/cat_source/es6/api/forgotPassword/forgotPassword.js
  public/js/cat_source/es6/components/modals/ForgotPasswordModal.js
Labels: Freddy

#2273 Improved project slugs
  composer.json
  composer.lock
  lib/Utils/Utils.php
Labels: Ready for prod, Freddy

#2275 Fix bulk error message
  public/js/cat_source/es6/actions/SegmentActions.js
Labels: Ready for prod, Freddy

#2276 FS Filestorage improved error message
  lib/Model/ConversionHandler.php
  lib/Model/FilesStorage/Exceptions/FileSystemException.php
  lib/Model/FilesStorage/FsFilesStorage.php
  lib/Model/FilesStorage/IFilesStorage.php
Labels: Ready for prod, Freddy

#2272 Fixed bufg in Create API
  lib/Controller/API/NewController.php
Labels: Ready for prod, Freddy

#2256 Fixing TM Search target
  lib/Utils/AsyncTasks/Workers/GetContributionWorker.php
  lib/Utils/Engines/Results/MyMemory/Matches.php
  nodejs/package-lock.json
Labels: Ready for prod, Freddy

#2281 🔥 Commonjs clean
  nodejs/package-lock.json
  public/js/cat_source/es6/actions/CatToolActions.js
  public/js/cat_source/es6/actions/ModalsActions.js
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/api/lexiqaIgnoreError/lexiqaIgnoreError.js
  public/js/cat_source/es6/components/header/Header.test.js
  public/js/cat_source/es6/components/header/TeamSelect.test.js
  public/js/cat_source/es6/components/header/cattol/JobMetadata.js
  public/js/cat_source/es6/components/header/cattol/search/Search.js
  public/js/cat_source/es6/components/header/manage/FilterProjects.js
  public/js/cat_source/es6/components/modals/CopySourceModal.js
  public/js/cat_source/es6/components/modals/CreateTeam.js
  public/js/cat_source/es6/components/modals/DQFModal.js
  public/js/cat_source/es6/components/modals/ModalWindow.js
  public/js/cat_source/es6/components/modals/ModalWindow.test.js
  public/js/cat_source/es6/components/modals/ModifyTeam.js
  public/js/cat_source/es6/components/modals/RevisionFeedbackModal.js
  public/js/cat_source/es6/components/modals/SplitJob.js
  public/js/cat_source/es6/components/outsource/AssignToTranslator.js
  public/js/cat_source/es6/components/outsource/OutsourceVendor.js
  public/js/cat_source/es6/components/projects/Dashboard.js
  public/js/cat_source/es6/components/projects/Dashboard.test.js
  public/js/cat_source/es6/components/projects/JobContainer.js
  public/js/cat_source/es6/components/projects/ProjectContainer.js
  public/js/cat_source/es6/components/review_extended/ReviewExtendedPanel.js
  public/js/cat_source/es6/components/segments/Segment.js
  public/js/cat_source/es6/components/segments/SegmentsContainer.js
  public/js/cat_source/es6/utils/commonUtils.js
  public/js/cat_source/es6/utils/lxq.main.js
  public/js/cat_source/ui.core.js
  public/js/cat_source/ui.events.js
  public/js/cat_source/ui.header.js
  public/js/cat_source/ui.review.js
  public/js/common.js
  public/js/login.js
  public/js/outsource.js
  public/js/tm.js
Labels: Ready for prod, Freddy, Plugin Dependencies

#2284 Fix ice propagation
  lib/Controller/setTranslationController.php
  lib/Utils/Autopropagation/PropagationAnalyser.php
Labels: Ready for prod, HotFix

#2283 Fix SQL file schema
  INSTALL/matecat.sql
  lib/Model/matecat.sql
  support_scripts/husky/.gitignore
  support_scripts/husky/pre-commit
Labels: Ready for prod, HotFix

#2296 Propagation fix for segments with different sizeRestriction
  lib/Utils/ProjectManager.php
Labels: Ready for prod, Freddy

#2291 Add enter key to start analysis
  Gruntfile.js
  public/css/sass/style.scss
  public/css/sass/upload-page.scss
  public/js/cat_source/ui.init.js
  public/js/new-project.js
  public/js/upload.js
Labels: Ready for prod

#2288 Fix cross-language matches
  lib/Controller/getContributionController.php
  lib/Utils/AsyncTasks/Workers/GetContributionWorker.php
  public/js/cat_source/es6/components/segments/SegmentFooterMultiMatches.js
Labels: Ready for prod, Freddy

#2286 Fix pre-translated segments
  lib/Utils/ProjectManager.php
Labels: Ready for prod, Freddy

#2298 Updated to subfiltering v1.0.15
  composer.lock
Labels: Ready for prod, Freddy

#2297 Transl encode fix
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/textUtils.js
Labels: Ready for prod
