Repository matecat/MateCat, pull requests merged in 2021-08, with the labels that each got.

#2148 Updated to subfiltering v1.0.10
  composer.lock
Labels: Freddy

#2157 Updated to xliff parser v1.0.73
  composer.lock
Labels: Freddy

#2158 Fixed Load issues with Global get Translation mismatches
  lib/Controller/getTranslationMismatchesController.php
  lib/Controller/getWarningController.php
  lib/Model/Segments/SegmentDao.php
Labels: Ready for prod, HotFix

#2160 Hot fix - Deleted status
  lib/Controller/API/V3/StatusController.php
  lib/Controller/analyzeController.php
  lib/Controller/catController.php
  lib/Controller/setTranslationController.php
  lib/Model/Analysis/AnalysisModel.php
  lib/Model/ChunkReviewTransition/ChunkReviewTransitionModel.php
  lib/Model/ChunkReviewTransition/UnitOfWork.php
  lib/Model/Features.php
  lib/Model/Projects/ProjectDao.php
  lib/Model/Segments/SegmentDao.php
  lib/Model/Segments/SegmentOriginalDataDao.php
  lib/Model/Teams/MembershipStruct.php
  lib/Plugins/Features/ReviewExtended/Model/QualityReportModel.php
  lib/Plugins/Features/TranslationVersions/Model/SegmentTranslationEventModel.php
  lib/Utils/Constants/JobStatus.php
Labels: Ready for prod, HotFix

#2167 Revise: show message on untranslated segments
  public/js/cat_source/es6/components/segments/Segment.js
Labels: Ready for prod

#2170 Updated to xliff parser v1.0.78
  composer.lock
Labels: Ready for prod, Freddy

#2166 fix php notice
  lib/Controller/AbstractControllers/ajaxController.php
  lib/Controller/createProjectController.php
  lib/Model/Segments/SegmentDao.php
  lib/Plugins/Features/Mmt.php
  lib/Plugins/Features/SecondPassReview.php
  lib/Utils/Filters.php
  lib/View/API/V2/Json/CreationStatus.php
  lib/View/API/V2/Json/UserMetadata.php
Labels: Ready for prod

#2175 Updated to Subfiltering v1.0.11
  composer.lock
Labels: Ready for prod, Freddy

#2179 ♻️ Refactoring api key requests
  Gruntfile.js
  public/js/cat_source/es6/ajax_utils/userAjax.js
  public/js/cat_source/es6/api/createUserApiKey/createUserApiKey.js
  public/js/cat_source/es6/api/createUserApiKey/index.js
  public/js/cat_source/es6/api/deleteUserApiKey/deleteUserApiKey.js
  public/js/cat_source/es6/api/deleteUserApiKey/index.js
  public/js/cat_source/es6/api/getUserApiKey/getUserApiKey.js
  public/js/cat_source/es6/api/getUserApiKey/index.js
  public/js/cat_source/es6/components/header/Header.test.js
  public/js/cat_source/es6/components/header/TeamSelect.test.js
  public/js/cat_source/es6/components/modals/PreferencesModal.js
Labels: Freddy

#2177 ♻️ Refactoring job api
  Gruntfile.js
  public/js/cat_source/es6/actions/CatToolActions.js
  public/js/cat_source/es6/actions/ModalsActions.js
  public/js/cat_source/es6/ajax_utils/jobAjax.js
  public/js/cat_source/es6/api/addJobTranslator/addJobTranslator.js
  public/js/cat_source/es6/api/addJobTranslator/index.js
  public/js/cat_source/es6/api/changeJobPassword/changeJobPassword.js
  public/js/cat_source/es6/api/changeJobPassword/index.js
  public/js/cat_source/es6/api/checkSplitRequest/checkSplitRequest.js
  public/js/cat_source/es6/api/checkSplitRequest/index.js
  public/js/cat_source/es6/api/confirmSplitRequest/confirmSplitRequest.js
  public/js/cat_source/es6/api/confirmSplitRequest/index.js
  public/js/cat_source/es6/api/getJobFileInfo/getJobFileInfo.js
  public/js/cat_source/es6/api/getJobFileInfo/index.js
  public/js/cat_source/es6/api/getJobMetadata/getJobMetadata.js
  public/js/cat_source/es6/api/getJobMetadata/index.js
  public/js/cat_source/es6/api/getJobStatistics/getJobStatistics.js
  public/js/cat_source/es6/api/getJobStatistics/index.js
  public/js/cat_source/es6/api/mergeJobChunks/index.js
  public/js/cat_source/es6/api/mergeJobChunks/mergeJobChunks.js
  public/js/cat_source/es6/api/sendRevisionFeedback/index.js
  public/js/cat_source/es6/api/sendRevisionFeedback/sendRevisionFeedback.js
  public/js/cat_source/es6/components/modals/RevisionFeedbackModal.js
  public/js/cat_source/es6/components/modals/SplitJob.js
  public/js/cat_source/es6/components/projects/Dashboard.js
  public/js/cat_source/es6/components/projects/Dashboard.test.js
  public/js/cat_source/es6/components/projects/JobContainer.js
  public/js/cat_source/es6/components/projects/ProjectContainer.js
  public/js/cat_source/es6/components/projects/ProjectsContainer.js
  public/js/cat_source/es6/utils/queryString/queryString.js
  public/js/cat_source/ui.header.js
  public/js/outsource.js
Labels: Freddy

#2180 ♻️ Refactoring team api
  Gruntfile.js
  public/js/analyze.js
  public/js/analyze.test.js
  public/js/cat_source/es6/actions/ManageActions.js
  public/js/cat_source/es6/actions/TeamsActions.js
  public/js/cat_source/es6/ajax_utils/teamAjax.js
  public/js/cat_source/es6/api/addUserTeam/addUserTeam.js
  public/js/cat_source/es6/api/addUserTeam/index.js
  public/js/cat_source/es6/api/createTeam/createTeam.js
  public/js/cat_source/es6/api/createTeam/index.js
  public/js/cat_source/es6/api/getTeamMembers/getTeamMembers.js
  public/js/cat_source/es6/api/getTeamMembers/index.js
  public/js/cat_source/es6/api/removeTeamUser/index.js
  public/js/cat_source/es6/api/removeTeamUser/removeTeamUser.js
  public/js/cat_source/es6/api/updateTeamName/index.js
  public/js/cat_source/es6/api/updateTeamName/updateTeamName.js
  public/js/cat_source/es6/components/header/Header.js
  public/js/cat_source/es6/components/header/TeamSelect.test.js
  public/js/cat_source/es6/components/modals/PreferencesModal.js
  public/js/cat_source/es6/components/projects/Dashboard.js
  public/js/cat_source/es6/components/projects/Dashboard.test.js
  public/js/cat_source/es6/components/projects/ProjectContainer.js
  public/js/cat_source/es6/stores/TeamsStore.js
  public/js/common.js
  public/js/login.js
  public/js/new-project.js
  public/js/user_store.js
Labels: Freddy
