Repository matecat/MateCat, pull requests merged in 2023-09, with the labels that each got.

#2869 Mm glossary search
  lib/Utils/AsyncTasks/Workers/GlossaryWorker.php
  lib/Utils/Engines/MyMemory.php
  lib/Utils/Engines/Results/MyMemory/SearchGlossaryResponse.php
Labels: Ready for prod

#2868 Fix new settings panel
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TranslationMemoryGlossaryTab.js
  public/js/cat_source/es6/pages/NewProject.js
Labels: Ready for prod

#2867 Show context group in messages tab
  public/js/cat_source/es6/components/segments/SegmentFooterTabMessages.js
Labels: Ready for prod

#2861 Track qa requests
  public/js/cat_source/es6/utils/lxq.main.js
Labels: In Progress

#2875 Settings panel fixes
  public/js/cat_source/es6/components/settingsPanel/SettingsPanel.js
  public/js/cat_source/es6/pages/CatTool.js
  public/js/cat_source/es6/pages/NewProject.js
Labels: Freddy

#2864 Count fullwidth chars as utf16
  public/js/cat_source/es6/utils/textUtils.js
Labels: Freddy

#2856 Updated en <> zh rate
  lib/Model/Analysis/PayableRates.php
Labels: dependencies, Ready for prod

#2892 Fix scroll manage page
  public/css/sass/commons/_manage.scss
  public/css/sass/upload-main.scss
  public/js/cat_source/es6/components/outsource/OutsourceContainer.js
Labels: Ready for prod

#2890 [Fix] On Segmentation rule change
  lib/Controller/API/NewController.php
  lib/Controller/convertFileController.php
  lib/Model/Conversion/ConvertedFileModel.php
  lib/Model/ConversionHandler.php
  lib/Model/ConversionHandlerOld.php
  lib/Model/FilesStorage/AbstractFilesStorage.php
  lib/Model/FilesStorage/FsFilesStorage.php
  lib/Model/FilesStorage/IFilesStorage.php
  lib/Model/FilesStorage/S3FilesStorage.php
  lib/Utils/Constants.php
  lib/Utils/Constants/ConversionHandlerStatus.php
  public/js/cat_source/es6/components/settingsPanel/Contents/AdvancedOptionsTab/SegmentationRule.js
  public/js/cat_source/es6/pages/NewProject.js
Labels: Ready for prod

#2889 Ignore Esc key to close segment when target is CJK
  public/js/cat_source/es6/components/segments/Segment.js
Labels: Ready for prod

#2882 Some fix new settings panel
  public/js/cat_source/es6/components/settingsPanel/Contents/AdvancedOptionsTab/CrossLanguagesMatches.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MessageNotification.js
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TMCreateResourceRow.js
  public/js/cat_source/es6/pages/NewProject.js
Labels: Ready for prod

#2895 Fix registration email links
  lib/View/Emails/Signup/welcome_content.html
Labels: Ready for prod

#2898 Hot fix password login check
  public/js/cat_source/es6/components/modals/LoginModal.js
Labels: Ready for prod

#2914 Fix: ai assistant switch
  public/js/cat_source/es6/components/settingsPanel/Contents/AdvancedOptionsTab/AiAssistant.js
Labels: Ready for prod
