Repository matecat/MateCat, pull requests merged in 2023-02, with the labels that each got.

#2648 Revert function getSegmentsIndex - SegmentStore
  public/js/cat_source/es6/stores/SegmentStore.js
Labels: Ready for prod, HotFix

#2646 Fix CJK regex characters counter
  public/js/cat_source/es6/utils/textUtils.js
Labels: Ready for prod

#2645 [QA_model] category label schema change
  inc/validation/schema/qa_model.json
  migrations/20230201162800_alter_qa_model_template_category_label.php
Labels: Ready for prod

#2654 Added hook to allow plugins to customize size-restrictions
  lib/Utils/LQA/QA.php
  lib/Utils/LQA/SizeRestriction.php
  test/unit/SizeRestrictionTest.php
Labels: Freddy

#2643 Team members search
  public/css/sass/common-modals.scss
  public/css/sass/commons/_sub-header.scss
  public/js/cat_source/es6/actions/ModalsActions.js
  public/js/cat_source/es6/components/header/manage/FilterProjects.js
  public/js/cat_source/es6/components/icons/IconClose.js
  public/js/cat_source/es6/components/modals/ModifyTeam.js
Labels: Ready for prod

#2652 MMT: remove add confirmation modal
  public/js/tm.js
Labels: Ready for prod

#2653 Ignore MT set contribution for engines id <= 1
  lib/Controller/setTranslationController.php
Labels: Ready for prod

#2670 ICE: change message on segment change
  public/js/cat_source/ui.core.js
Labels: Ready for prod

#2669 Xliff parser 1.0.105
  composer.lock
Labels: Ready for prod

#2668 Subfiltering v1.1.17
  composer.lock
Labels: Ready for prod

#2665 [Glossary] Fix glossary payload
  lib/Controller/API/App/GlossaryController.php
  lib/Model/GlossaryModel.php
Labels: Ready for prod

#2663 [MMT] Fix "Engine not found" error
  lib/Plugins/Features/Mmt.php
Labels: Ready for prod

#2661 Fixed issues with upload token
  ___composer.lock
  lib/Controller/ajaxUtilsController.php
  lib/Controller/newProjectController.php
  lib/Utils/Utils.php
Labels: Ready for prod

#2658 Segments filter fix
  public/css/sass/components/header/segmentsFilter.scss
  public/js/cat_source/es6/components/header/cattol/segment_filter/SegmentsFilter.js
Labels: Ready for prod

#2672 [QA Template] fix api http status
  lib/Controller/API/V3/QAModelTemplateController.php
Labels: Ready for prod

#2660 Fixed QA Template Model validation
  lib/Model/QAModelTemplate/QAModelTemplateDao.php
  lib/Utils/Validator/JSONValidator.php
Labels: Ready for prod

#2655 New size restriction logics
  lib/Utils/CJKLangUtils.php
  lib/Utils/EmojiUtils.php
  lib/Utils/LQA/SizeRestriction.php
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/textUtils.js
  public/js/cat_source/es6/utils/textUtils.js
Labels: Ready for prod, Plugin Dependencies

#2634 [API] V3 Jobs standard_word_count fix
  lib/Model/Chunks/ChunkDao.php
  lib/Model/Jobs/JobDao.php
  lib/View/API/V3/Json/Chunk.php
Labels: Ready for prod

#2644 Added size restriction to the endpoint /v3/word-count/raw
  lib/Controller/API/V3/CountWordController.php
  lib/Utils/LQA/QA.php
  lib/Utils/LQA/SizeRestriction.php
  test/unit/SizeRestrictionTest.php
Labels: Ready for prod

#2675 Tm search case insensitive
  public/js/tm.js
Labels: Ready for prod

#2678 Fix setting project name from query string parameter
  public/js/cat_source/es6/pages/NewProject.js
Labels: Freddy
