Repository matecat/MateCat, pull requests merged in 2023-01, with the labels that each got.

#2609 [Subfiltering] Skyscanner syntax + fixes
  composer.lock
Labels: Ready for prod

#2604 Glossary: if present give priority to glossary highlight
  public/js/cat_source/es6/components/segments/Editarea.js
Labels: Ready for prod

#2602 History pushState with segment id
  public/js/cat_source/es6/components/segments/Segment.js
Labels: Ready for prod

#2598 Tab notes allowed link redirect
  public/js/cat_source/es6/components/segments/SegmentFooterTabMessages.js
  public/js/cat_source/es6/utils/commonUtils.js
  public/js/cat_source/es6/utils/textUtils.js
Labels: Ready for prod, Freddy, Plugin Dependencies

#2597 Local storage selected keys glossary
  public/js/cat_source/es6/components/segments/SegmentFooterTabGlossary/KeysSelect.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabGlossary/SegmentFooterTabGlossary.js
  public/js/cat_source/es6/utils/segmentUtils.js
Labels: Ready for prod

#2526 Added Santali language
  lib/Utils/Langs/supported_langs.json
Labels: Ready for prod

#2621 Glossary CSV header validation improvement
  lib/Utils/Utils.php
  lib/Utils/Validator/GlossaryCSVValidator.php
  test/support/files/csv/glossary/NV - Header vuoto.csv
  test/support/files/csv/glossary/V - Header-vuoti.csv
  test/support/functions.php
  test/support/php_versions_override.php
  test/test_helper.php
  test/unit/Validator/GlossaryCSVValidatorTest.php
Labels: Ready for prod

#2616 Glossary list alphabetical order
  public/js/cat_source/es6/components/segments/SegmentFooterTabGlossary/SegmentFooterTabGlossary.js
Labels: Ready for prod

#2613 [Import glossary] - Change error message
  lib/Utils/Validator/GlossaryCSVValidator.php
Labels: Ready for prod

#2627 Fix split jsont projects
  public/js/cat_source/es6/stores/SegmentStore.js
Labels: Ready for prod

#2625 Fix glossary regex start index
  public/js/cat_source/es6/utils/textUtils.js
Labels: Ready for prod

#2624 Fix error search results navigation
  public/js/cat_source/es6/stores/SegmentStore.js
Labels: Ready for prod

#2618 Analysis Page: Change NOT_TO_ANALYZE message
  public/css/sass/commons/_analyze.scss
  public/js/cat_source/es6/components/analyze/AnalyzeHeader.js
Labels: Ready for prod

#2617 Hide tm lookup/update checkbox for no owner users
  lib/View/tm.html
  public/css/sass/common.scss
  public/js/tm.js
Labels: Ready for prod

#2615 QA improvement (check for id mismatch)
  lib/Utils/QA.php
Labels: Ready for prod

#2611 Character limits
  .gitignore
  INSTALL/matecat.sql
  composer.json
  lib/Controller/getWarningController.php
  lib/Controller/loadTMXController.php
  lib/Controller/setTranslationController.php
  lib/Model/EditLog/EditLogSegmentStruct.php
  lib/Model/QualityReport/QualityReportSegmentStruct.php
  lib/Model/matecat.sql
  lib/Plugins/Features/QaCheckGlossary.php
  lib/Utils/Analysis/Workers/TMAnalysisWorker.php
  lib/Utils/CJKLangUtils.php
  lib/Utils/EmojiUtils.php
  lib/Utils/LQA/BxExG/Element.php
  lib/Utils/LQA/BxExG/Mapper.php
  lib/Utils/LQA/BxExG/Validator.php
  lib/Utils/LQA/QA.php
  lib/Utils/LQA/SizeRestriction.php
  lib/Utils/PostProcess.php
  lib/Utils/ProjectManager.php
  lib/Utils/TaskRunner/Executor.php
  lib/Utils/Validator/GlossaryCSVValidator.php
  lib/Utils/XliffReplacer/XliffReplacerCallback.php
  lib/View/API/V2/Json/QAGlobalWarning.php
  lib/View/API/V2/Json/QALocalWarning.php
  lib/View/API/V2/Json/QAWarning.php
  public/js/cat_source/es6/components/segments/Editarea.js
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/index.js
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/textUtils.js
  public/js/cat_source/es6/utils/textUtils.js
  test/support/functions.php
  test/support/lib/AbstractTest.php
  test/support/php_versions_override.php
  test/test_helper.php
  test/unit/SizeRestrictionTest.php
  test/unit/TagPositionTest.php
  test/unit/XliffParserTest.php
Labels: Ready for prod, Plugin Dependencies

#2629 Upload tmx: set max files upload to 10
  public/js/tm.js
Labels: Ready for prod

#2628 Update untranslated content modal
  public/js/cat_source/es6/actions/ModalsActions.js
  public/js/cat_source/es6/components/projects/Dashboard.js
  public/js/cat_source/ui.core.js
Labels: Ready for prod

#2520 Fixed advancement w.c. for pre-translated on R1/R2
  inc/Bootstrap.php
  lib/Controller/API/V2/Validators/SegmentTranslationIssueValidator.php
  lib/Controller/getSearchController.php
  lib/Controller/getSegmentsController.php
  lib/Controller/setTranslationController.php
  lib/Plugins/Features/AbstractRevisionFeature.php
  lib/Plugins/Features/ReviewExtended/SegmentTranslationModel.php
  lib/Plugins/Features/TranslationVersions.php
  lib/Plugins/Features/TranslationVersions/Handlers/DummyTranslationVersionHandler.php
  lib/Plugins/Features/TranslationVersions/Handlers/TranslationEventsHandler.php
  lib/Plugins/Features/TranslationVersions/Handlers/TranslationVersionsHandler.php
  lib/Plugins/Features/TranslationVersions/Model/TranslationEvent.php
  lib/Plugins/Features/TranslationVersions/VersionHandlerInterface.php
Labels: Ready for prod

#2630 [Quality summary] Normalize limit object
  lib/Model/LQA/ModelStruct.php
Labels: Ready for prod

#2440 MMT code update
  INSTALL/matecat.sql
  composer.json
  lib/Controller/AbstractControllers/BaseKleinViewController.php
  lib/Controller/AbstractControllers/viewController.php
  lib/Controller/engineController.php
  lib/Controller/setTranslationController.php
  lib/Controller/userKeysController.php
  lib/Model/EnginesModel/EngineStruct.php
  lib/Model/EnginesModel/MMTStruct.php
  lib/Model/Jobs/JobStruct.php
  lib/Model/Users/MetadataDao.php
  lib/Model/matecat.sql
  lib/Plugins/Features/Mmt.php
  lib/Plugins/Features/Mmt/static/build/mmt_extensions.js
  lib/Utils/Analysis/Workers/FastAnalysis.php
  lib/Utils/Analysis/killAnalysis.sh
  lib/Utils/Analysis/restartAnalysis.sh
  lib/Utils/AsyncTasks/Workers/GetContributionWorker.php
  lib/Utils/AsyncTasks/Workers/SetContributionMTWorker.php
  lib/Utils/AsyncTasks/Workers/SetContributionWorker.php
  lib/Utils/Constants/Engines.php
  lib/Utils/Engines/MMT.php
  lib/Utils/Engines/MMT/MMTServiceApi.php
  lib/Utils/TmKeyManagement/Filter.php
  lib/View/mt_engines.html
  public/css/sass/common.scss
  public/css/sass/components/common/Select.scss
  public/img/info.png
  public/js/cat_source/es6/api/downloadGlossary/downloadGlossary.js
  public/js/cat_source/es6/components/modals/PreferencesModal.js
  public/js/cat_source/es6/components/projects/JobContainer.js
  public/js/cat_source/es6/components/projects/ProjectContainer.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabGlossary/TermForm.js
  public/js/gdrive.picker.js
  public/js/tm.js
Labels: Ready for prod
