Repository matecat/MateCat, pull requests merged in 2023-12, with the labels that each got.

#3012 Fix Dari language
  lib/Utils/Langs/supported_langs.json
Labels: Ready for prod, HotFix

#3016 [Project manager] Exclude projects with status NOT_TO_ANALYZE
  lib/Utils/ManageUtils.php
Labels: Ready for prod

#3013 Mark projects created via API
  lib/Controller/API/NewController.php
  lib/Routes/api_v3_routes.php
  lib/Utils/ProjectManager.php
  lib/View/API/V2/Json/Project.php
Labels: Ready for prod

#3021 Add model id v3 jobs
  lib/View/API/V3/Json/QualitySummary.php
  public/api/swagger-source.js
Labels: Ready for prod

#3024 Fix QualitySummary
  lib/View/API/V3/Json/QualitySummary.php
Labels: HotFix

#3000 DeepL integration
  lib/Controller/API/NewController.php
  lib/Controller/API/V3/DeepLGlossaryController.php
  lib/Controller/API/V3/MetaDataController.php
  lib/Controller/API/V3/ModernMTController.php
  lib/Controller/createProjectController.php
  lib/Controller/engineController.php
  lib/Model/EnginesModel/DeepLStruct.php
  lib/Model/EnginesModel/EngineDAO.php
  lib/Model/Projects/MetadataDao.php
  lib/Model/Projects/MetadataStruct.php
  lib/Routes/api_v3_routes.php
  lib/Utils/AsyncTasks/Workers/GetContributionWorker.php
  lib/Utils/Constants/Engines.php
  lib/Utils/Engines/AbstractEngine.php
  lib/Utils/Engines/DeepL.php
  lib/Utils/Engines/DeepL/DeepLApiClient.php
  lib/Utils/Engines/DeepL/DeepLApiException.php
  lib/Utils/Engines/MMT.php
  lib/Utils/Engines/MMT/MMTServiceApi.php
  lib/Utils/Files/CSV.php
  lib/Utils/ProjectManager.php
  lib/Utils/Validator/DeepLValidator.php
  lib/Utils/Validator/EngineValidator.php
  lib/Utils/Validator/MMTValidator.php
  public/css/sass/components/settingsPanel/MachineTranslationTab.scss
  public/css/sass/components/settingsPanel/TranslationMemoryGlossaryTab.scss
  public/js/cat_source/es6/actions/CatToolActions.js
  public/js/cat_source/es6/api/createMemoryAndImportGlossary/createMemoryAndImportGlossary.js
  public/js/cat_source/es6/api/createMemoryAndImportGlossary/index.js
  public/js/cat_source/es6/api/deleteMemoryGlossary/deleteMemoryGlossary.js
  public/js/cat_source/es6/api/deleteMemoryGlossary/index.js
  public/js/cat_source/es6/api/getMMTKeys/getMMTKeys.js
  public/js/cat_source/es6/api/getMMTKeys/index.js
  public/js/cat_source/es6/api/getStatusMemoryGlossaryImport/getStatusMemoryGlossaryImport.js
  public/js/cat_source/es6/api/getStatusMemoryGlossaryImport/index.js
  public/js/cat_source/es6/api/importMemoryGlossary/importMemoryGlossary.js
  public/js/cat_source/es6/api/importMemoryGlossary/index.js
  public/js/cat_source/es6/api/updateMemoryGlossary/index.js
  public/js/cat_source/es6/api/updateMemoryGlossary/updateMemoryGlossary.js
  public/js/cat_source/es6/components/header/cattol/JobMetadata.js
  public/js/cat_source/es6/components/icons/IconEdit.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MTGlossary.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MTGlossaryCreateRow.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MTGlossaryRow.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MTRow.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MachineTranslationTab.js
  public/js/cat_source/es6/constants/CatToolConstants.js
  public/js/cat_source/es6/pages/NewProject.js
  public/js/cat_source/es6/stores/CatToolStore.js
Labels: In Progress

#3034 Fix MMT glossary case sensitive flag
  public/js/cat_source/es6/pages/NewProject.js
Labels: Ready for prod

#3004 [API] Share key with a user
  lib/Controller/API/V3/MyMemoryController.php
  lib/Controller/userKeysController.php
  lib/Routes/api_v3_routes.php
  lib/Utils/TmKeyManagement/TmKeyManagement.php
  lib/Utils/Utils.php
Labels: Freddy

#3037 Fix crash when no MT keys is selected
  public/js/cat_source/es6/pages/NewProject.js
Labels: Ready for prod

#3072 [Subfiltering] Fix Emoji
  composer.lock
Labels: Freddy
