Repository matecat/MateCat, pull requests merged in 2023-05, with the labels that each got.

#2741 Mmt engine set by default for Translated users
  lib/Controller/AbstractControllers/viewController.php
  lib/Controller/catController.php
  lib/Controller/newProjectController.php
  lib/View/tm.html
Labels: dependencies, Ready for prod

#2746 Add link preview images
  lib/View/analyze.html
  lib/View/index.html
  lib/View/jobAnalysis.html
  lib/View/manage.html
Labels: Ready for prod

#2739 Restore segment analysis API
  lib/Controller/API/App/SegmentAnalysisController.php
  lib/Model/Segments/SegmentDao.php
  lib/Routes/utils_routes.php
Labels: Ready for prod

#2751 Sentry fix
  public/js/cat_source/es6/api/deleteSegmentIssue/deleteSegmentIssue.js
  public/js/cat_source/es6/api/setTranslation/setTranslation.js
  public/js/cat_source/es6/components/analyze/ProjectAnalyze.js
  public/js/cat_source/es6/pages/NewProject.js
  public/js/cat_source/review_extended/review_extended.ui_extension.js
  public/js/tm.js
Labels: Ready for prod

#2752 Added `notes` node to the API
  lib/Controller/API/App/SegmentAnalysisController.php
Labels: Ready for prod

#2745 Create project API authentication mandatory
  lib/Controller/API/NewController.php
Labels: Ready for prod

#2756 Create project API authentication mandatory (which was reverted)
  lib/Controller/API/NewController.php
Labels: Ready for prod

#2760 Fix GlossaryWorker
  lib/Utils/AsyncTasks/Workers/GlossaryWorker.php
Labels: Ready for prod

#2762 Refactoring API segments
  lib/Controller/API/App/SegmentAnalysisController.php
  lib/Model/LQA/EntryDao.php
  lib/Model/Segments/SegmentMetadataDao.php
  lib/Model/Segments/SegmentNoteDao.php
Labels: Ready for prod

#2759 getContributionWorker improvement
  lib/Utils/AsyncTasks/Workers/GetContributionWorker.php
  lib/Utils/TMS/TMSService.php
Labels: Ready for prod

#2763 Reviewed some error codes
  lib/Utils/ProjectManager.php
Labels: Ready for prod

#2764 [API] Limit pagination
  lib/Controller/getSegmentsController.php
  lib/Plugins/Features/ReviewExtended/Controller/API/QualityReportController.php
Labels: Ready for prod

#2717 Ai assistant
  composer.json
  composer.lock
  inc/INIT.php
  inc/config.ini.sample
  inc/task_manager_config.ini.sample
  lib/Controller/API/App/AIAssistantController.php
  lib/Controller/API/App/GlossaryController.php
  lib/Controller/API/V2/KleinController.php
  lib/Controller/AbstractControllers/viewController.php
  lib/Routes/utils_routes.php
  lib/Utils/AIAssistant/Client.php
  lib/Utils/AsyncTasks/Workers/AIAssistantWorker.php
  lib/Utils/AsyncTasks/Workers/GlossaryWorker.php
  lib/Utils/TaskRunner/Commons/AbstractWorker.php
  lib/Utils/Utils.php
  lib/View/analyze.html
  lib/View/index.html
  lib/View/jobAnalysis.html
  lib/View/manage.html
  lib/View/tm.html
  lib/View/upload.html
  nodejs/server.js
  public/css/sass/components/segment/segmentFooterTabAiAssistant.scss
  public/css/sass/main.scss
  public/css/sass/style.scss
  public/js/advancedOptionsTab.js
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/api/aiSuggestion/aiSuggestion.js
  public/js/cat_source/es6/api/aiSuggestion/index.js
  public/js/cat_source/es6/components/icons/Assistant.js
  public/js/cat_source/es6/components/icons/Education.js
  public/js/cat_source/es6/components/icons/IconCloseCircle.js
  public/js/cat_source/es6/components/icons/IconDislike.js
  public/js/cat_source/es6/components/icons/IconLike.js
  public/js/cat_source/es6/components/outsource/OutsourceVendor.js
  public/js/cat_source/es6/components/segments/SegmentFooter.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabAiAssistant.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabConcordance.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabGlossary/SegmentFooterTabGlossary.js
  public/js/cat_source/es6/components/segments/SegmentSource.js
  public/js/cat_source/es6/components/segments/TabConcordanceResults.js
  public/js/cat_source/es6/constants/SegmentConstants.js
  public/js/cat_source/es6/sse/sse.js
  public/js/cat_source/es6/stores/SegmentStore.js
  public/js/cat_source/es6/utils/commonUtils.js
  public/js/cat_source/es6/utils/segmentUtils.js
Labels: Ready for prod, Plugin Dependencies

#2772 Revert urdu font
  lib/View/activity_log.html
  lib/View/analyze.html
  lib/View/index.html
  lib/View/jobAnalysis.html
  lib/View/manage.html
  lib/View/mt_engines.html
  lib/View/revise_summary.html
  lib/View/tm.html
  lib/View/upload.html
  lib/View/xliffToTarget.html
  public/css/sass/components/segment/segment.scss
  public/css/sass/style.scss
Labels: Ready for prod

#2771 Ai assistant
  lib/Utils/AsyncTasks/Workers/AIAssistantWorker.php
  lib/View/tm.html
  public/css/sass/style.scss
  public/js/advancedOptionsTab.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabAiAssistant.js
  public/js/cat_source/es6/components/segments/SegmentSource.js
  public/js/cat_source/es6/utils/segmentUtils.js
Labels: Ready for prod

#2777 Ai assistant send source string without entities
  public/js/cat_source/es6/components/segments/SegmentFooterTabAiAssistant.js
Labels: Ready for prod

#2773 Emoji fix
  composer.lock
Labels: Ready for prod

#2778 Update supported file list in api doc page
  lib/View/APIDoc.php
  public/css/sass/common.scss
Labels: Ready for prod

#2718 [Raw word count] count placeholders as 1 word
  composer.lock
  lib/Utils/CatUtils.php
  lib/Utils/ProjectManager.php
  test/unit/Utils/CatUtilsTest.php
Labels: Ready for prod

#2754 MMT new languages
  lib/Utils/Langs/supported_langs.json
Labels: Ready for prod

#2776 Tab Matches key name ellipsis
  public/css/sass/common.scss
  public/css/sass/components/segment/segmentFooterTabGlossary.scss
  public/css/sass/style.scss
  public/js/cat_source/es6/components/common/LabelWithTooltip.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabGlossary/GlossaryItem.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabMatches.js
Labels: Ready for prod

#2774 Job instructions updates
  public/js/cat_source/es6/components/common/VirtualList/Rows/RowSegment.js
  public/js/cat_source/es6/components/header/cattol/JobMetadata.js
  public/js/cat_source/es6/components/modals/JobMetadataModal.js
  public/js/cat_source/es6/utils/commonUtils.js
Labels: Ready for prod

#2786 Fix job total_word_count update after splitting a job
  lib/Model/Jobs/JobDao.php
  lib/Utils/ProjectManager.php
Labels: Ready for prod

#2790 Added Oriya language
  lib/Utils/Langs/supported_langs.json
Labels: Ready for prod

#2789 Fixes on language changes crash
  lib/Decorator/CatDecorator.php
  public/js/cat_source/es6/components/footer/CattoolFooter.js
Labels: Ready for prod
