Repository matecat/MateCat, pull requests merged in 2023-03, with the labels that each got.

#2685 Payable rates changes
  lib/Model/Analysis/PayableRates.php
  lib/Utils/ProjectManager.php
Labels: In Progress

#2686 Fix copyAllSource2Target (splitted jobs)
  lib/Controller/copyAllSource2TargetController.php
Labels: Ready for prod

#2683 Fix change case buttons activation by keyboard
  public/js/cat_source/es6/components/segments/Editarea.js
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/getSelectedTextWithoutEntities.js
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/index.js
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/replaceMultipleText.js
Labels: Ready for prod

#2680 Add macro for header import
  lib/View/activity_log.html
  lib/View/analyze.html
  lib/View/editlog.html
  lib/View/jobAnalysis.html
  lib/View/revise_summary.html
  lib/View/xliffToTarget.html
  public/js/cat_source/es6/components/outsource/OutsourceVendor.js
  public/js/cat_source/es6/components/projects/JobContainer.js
Labels: Ready for prod, Plugin Dependencies

#2691 Upload error handling :
  favicon.ico
  public/img/meta/favicon-16x16.svg
  public/js/lib/fileupload/main.js
Labels: Ready for prod

#2692 Not logged in removed get keys list request
  public/js/cat_source/es6/pages/NewProject.js
Labels: Ready for prod

#2690 Fix delete contriubution
  lib/Utils/TmKeyManagement/TmKeyManagement.php
  public/js/cat_source/es6/components/segments/SegmentFooterTabMatches.js
Labels: Ready for prod

#2693 [Glossary validation] Fix http code
  lib/Controller/API/App/GlossaryController.php
Labels: Ready for prod

#2695 Track sse channel errors
  public/js/cat_source/es6/api/initFileUpload/initFileUpload.js
  public/js/cat_source/es6/sse/sse.js
  public/js/cat_source/es6/utils/commonUtils.js
Labels: Ready for prod

#2626 New fast analysis
  lib/Utils/Analysis/Workers/FastAnalysis.php
  lib/Utils/Analysis/Workers/TMAnalysisWorker.php
  lib/Utils/CatUtils.php
  lib/Utils/Engines/MyMemory.php
Labels: need clarification, Ready for prod

#2697 Sentry fix
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/components/header/cattol/FilesMenu.js
  public/js/cat_source/es6/hooks/useSegmentsLoader.js
  public/js/cat_source/es6/pages/CatTool.js
  public/js/cat_source/es6/pages/NewProject.js
  public/js/cat_source/es6/sse/sse.js
  public/js/cat_source/es6/stores/SegmentStore.js
  public/js/cat_source/ui.core.js
  public/js/cat_source/ui.init.js
Labels: Ready for prod

#2699 Fix for glossary get
  lib/Controller/API/App/GlossaryController.php
Labels: Ready for prod

#2694 Segment metadata fix (dropped unique key)
  lib/Controller/API/App/SegmentAnalysisController.php
  lib/Model/Segments/SegmentMetadataDao.php
  lib/Utils/LQA/QA.php
  migrations/20230308162800_alter_segment_metadata_index.php
Labels: Ready for prod

#2689 Update footer style
  public/css/sass/common.scss
  public/css/sass/commons/_nav-bar.scss
  public/js/cat_source/es6/components/footer/Footer.js
  public/js/cat_source/es6/components/header/Header.js
  public/js/cat_source/es6/components/outsource/OutsourceVendor.js
Labels: Ready for prod

#2710 Fix infinite render when get empty segments
  public/css/sass/components/common/CookieConsent.scss
  public/js/cat_source/es6/components/analyze/AnalyzeChunksResume.js
  public/js/cat_source/es6/components/analyze/AnalyzeMain.js
  public/js/cat_source/es6/pages/CatTool.js
Labels: Ready for prod
