Repository matecat/MateCat, pull requests merged in 2023-06, with the labels that each got.

#2798 Subfiltering 1.2.2
  composer.lock
Labels: Ready for prod

#2795 Fix tab concordance tag displaying
  public/js/cat_source/es6/components/segments/TabConcordanceResults.js
Labels: Ready for prod

#2793 Css fix: export TMX loader
  public/css/sass/common.scss
Labels: Ready for prod

#2788 Ai assistant feedback behaviour
  public/css/sass/components/segment/segmentFooterTabAiAssistant.scss
  public/js/cat_source/es6/components/segments/SegmentFooterTabAiAssistant.js
Labels: Ready for prod

#2794 Fix segment raw word count function
  lib/Utils/CatUtils.php
  test/unit/Utils/CatUtilsTest.php
Labels: Ready for prod

#2799 Quality report API refactoring
  inc/version.ini
  lib/Model/QualityReport/QualityReportSegmentModel.php
Labels: Ready for prod

#2800 Fix Invalid integer field value
  lib/Model/ProjectManager/ProjectManagerModel.php
  lib/Utils/ProjectManager.php
Labels: Ready for prod

#2801 Fix API v3 for segment analysis
  lib/Controller/API/App/SegmentAnalysisController.php
  lib/Model/Jobs/JobDao.php
Labels: Freddy

#2814 Fix jsont2 file icon
  public/js/cat_source/es6/components/common/VirtualList/Rows/RowSegment.js
  public/js/cat_source/es6/utils/commonUtils.js
Labels: Ready for prod

#2812 Pre-translations correct state
  composer.lock
  lib/Utils/ProjectManager.php
  lib/Utils/TaskRunner/Executor.php
Labels: Ready for prod

#2811 Fix broken urls
  public/js/cat_source/es6/components/header/cattol/MarkAsCompleteButton.js
  public/js/cat_source/es6/components/quality_report/ProductionSummary.js
Labels: Ready for prod

#2809 Fix get concordance request AI assistant
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabAiAssistant.js
Labels: Ready for prod

#2805 Fix mmt matches (missing source and target)
  inc/version.ini
  lib/Utils/Engines/MMT.php
Labels: Ready for prod

#2796 Update ph tags regexp
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/tagModel.js
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/textUtils.js
  public/js/cat_source/es6/utils/tagUtils.js
Labels: Ready for prod

#2807 Swagger docs
  inc/version.ini
  public/api/swagger-source.js
Labels: Ready for prod

#2810 Fix for saving notes
  lib/Model/ProjectManager/ProjectManagerModel.php
Labels: Ready for prod

#2817 [API Segment analysis] Fix for issues (grouped by id job)
  lib/Controller/API/App/SegmentAnalysisController.php
Labels: Ready for prod

#2821 New payable rates
  lib/Model/Analysis/PayableRates.php
Labels: Ready for prod

#2824 Disable outsource for specific users feature
  lib/Model/Analysis/AbstractStatus.php
  lib/Model/Analysis/AnalysisDao.php
  lib/View/API/V2/Json/Job.php
Labels: Ready for prod, Plugin Dependencies

#2818 Fix pre-translations (ignoring initial states)
  lib/Utils/ProjectManager.php
Labels: Ready for prod

#2816 XliffReplacerCallback fix
  lib/Utils/XliffReplacer/XliffReplacerCallback.php
  test/unit/Utils/XliffReplacerCallbackTest.php
Labels: Ready for prod

#2825 Fix: job jsont2 and other files type
  public/js/cat_source/es6/components/common/VirtualList/Rows/RowSegment.js
Labels: Ready for prod

#2827 Glossary schema payload changes
  inc/validation/schema/glossary/delete.json
  inc/validation/schema/glossary/set.json
  inc/validation/schema/glossary/update.json
Labels: Ready for prod
