Repository matecat/MateCat, pull requests merged in 2024-11, with the labels that each got.

#3644 API docs (v1/new)
  public/api/swagger-source.js
Labels: Ready for prod

#3636 Show error when try to perform a replace all over segments in revised state
  .gitignore
  index.php
  lib/Controller/getSearchController.php
Labels: Ready for prod

#3612 api/v1/new documentation
  public/api/swagger-source.js
Labels: Ready for prod

#3605 Fix auto-propagation of segments in R2
  lib/Model/Segments/SegmentDao.php
Labels: Ready for prod

#3615 [Security] Rate limiter on key check
  lib/Controller/API/App/Authentication/LoginController.php
  lib/Controller/API/V2/KeyCheckController.php
Labels: Ready for prod, Freddy

#3649 /api/v2/projects/{id_project}/{password}/r2 documentation
  public/api/swagger-source.js
Labels: Freddy

#3512 Fix regex tag transformation
  public/js/cat_source/es6/utils/textUtils.js
Labels: Ready for prod, Freddy

#3611 Job not splittable - fix modal
  public/css/sass/modals/split_modal.scss
  public/js/cat_source/es6/components/modals/SplitJob.js
Labels: Freddy

#3489 Segment filter: fix behaviour
  public/js/cat_source/es6/components/header/cattol/segment_filter/SegmentsFilter.js
  public/js/cat_source/es6/components/header/cattol/segment_filter/segment_filter.js
  public/js/cat_source/es6/components/segments/Segment.js
  public/js/cat_source/es6/components/segments/SegmentButtons.js
  public/js/cat_source/es6/pages/CatTool.js
Labels: Freddy, on Hold

#3616 Fix upload files with same hash (= same content)
  lib/Utils/ProjectManager.php
Labels: Freddy

#3655 Fix MMT translate
  lib/Utils/Engines/MMT/MMTServiceApi.php
Labels: Freddy

#3656 Fix download analysis report
  lib/Controller/downloadAnalysisReportController.php
Labels: Ready for prod

#3657 Check flag sse clientConnected when it's in pending
  public/js/cat_source/es6/components/segments/SegmentFooter.js
  public/js/cat_source/es6/components/segments/SegmentFooterMultiMatches.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabConcordance.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabGlossary/SegmentFooterTabGlossary.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabMatches.js
  public/js/cat_source/es6/components/segments/SegmentsContainer.js
  public/js/cat_source/es6/sse/SseListener.js
Labels: Ready for prod

#3659 JobStruct `is_review` default value
  lib/Model/Jobs/JobStruct.php
Labels: Ready for prod, Freddy

#3660 Manage segments filter api error
  public/js/cat_source/es6/actions/CatToolActions.js
  public/js/cat_source/es6/components/header/cattol/segment_filter/SegmentsFilter.js
  public/js/cat_source/es6/components/header/cattol/segment_filter/segment_filter.js
  public/js/cat_source/es6/constants/CatToolConstants.js
  public/js/cat_source/es6/stores/CatToolStore.js
Labels: Ready for prod

#3661 Fixed crash on empty string on word count
  lib/Utils/CatUtils.php
Labels: Ready for prod

#3662 Fixed assign a job to a translator
  lib/Utils/Email/SendToTranslatorAbstract.php
Labels: Ready for prod

#3663 Fix: The logout should not log out all browsers
  lib/Controller/API/App/Authentication/LoginController.php
  lib/Controller/API/Commons/Authentication/AuthenticationTrait.php
  lib/Routes/utils_routes.php
Labels: Ready for prod

#3666 Sentry fix
  public/js/cat_source/es6/components/segments/Segment.js
Labels: Ready for prod

#3669 Fix segment split
  lib/Model/DataAccess/AbstractDao.php
Labels: Ready for prod

#3670 Fixed broken API page
  lib/View/templates/_APIDoc.php
Labels: Ready for prod

#3671 Sentry fix
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/components/header/cattol/search/Search.js
  public/js/cat_source/es6/components/review_extended/ReviewExtendedIssuePanel.js
  public/js/cat_source/es6/utils/commonUtils.js
  public/js/cat_source/ui.core.js
Labels: Ready for prod

#3683 Fix: concurrency issue in shortcuts to confirm segments
  public/js/cat_source/es6/components/segments/Editarea.js
  public/js/cat_source/es6/components/segments/SegmentButtons.js
Labels: Ready for prod

#3674 Sentry fix 12 Nov
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/api/downloadFile/downloadFile.js
  public/js/cat_source/es6/api/downloadFile/index.js
  public/js/cat_source/es6/components/review_extended/ReviewExtendedIssuePanel.js
  public/js/cat_source/es6/components/segments/Segment.js
  public/js/cat_source/es6/components/segments/SegmentButtons.js
  public/js/cat_source/es6/components/segments/SegmentsContainer.js
  public/js/cat_source/es6/components/segments/utils/translationMatches.js
  public/js/cat_source/es6/pages/NewProject.js
  public/js/cat_source/es6/utils/commonUtils.js
  public/js/cat_source/es6/utils/downloadFileUtils.js
  public/js/cat_source/ui.core.js
Labels: Ready for prod

#3688 Fix: duplicate notifications
  lib/View/templates/_signin.html
  public/js/cat_source/es6/components/notificationsComponent/NotificationItem.js
  public/js/cat_source/es6/pages/AnalyzePage.js
  public/js/cat_source/es6/pages/CatTool.js
  public/js/cat_source/es6/pages/SignIn.js
Labels: Ready for prod

#3696 Fix MATECAT-3H1 sentry
  public/js/cat_source/ui.core.js
Labels: Ready for prod

#3692 Fix tab editor settings
  lib/Controller/newProjectController.php
  lib/Decorator/CatDecorator.php
  lib/Model/LexiQA/LexiQADecorator.php
  lib/View/templates/_index.html
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/components/header/cattol/Header.js
  public/js/cat_source/es6/components/header/cattol/SubHeaderContainer.js
  public/js/cat_source/es6/components/header/cattol/search/Search.js
  public/js/cat_source/es6/components/segments/SegmentsContainer.js
  public/js/cat_source/es6/components/settingsPanel/Contents/EditorSettingsTab/GuessTag.js
  public/js/cat_source/es6/hooks/useAuth.js
  public/js/cat_source/es6/pages/CatTool.js
  public/js/cat_source/es6/pages/SignIn.js
  public/js/cat_source/es6/utils/lxq.main.js
  public/js/cat_source/es6/utils/segmentUtils.js
Labels: Ready for prod

#3687 Make the My Projects link clickable with ctrl+click
  public/css/sass/components/common/UserMenu.scss
  public/js/cat_source/es6/components/header/Header.js
  public/js/cat_source/es6/components/header/UserMenu.js
  public/js/cat_source/es6/components/header/cattol/Header.js
  public/js/cat_source/es6/pages/QualityReport.js
Labels: Ready for prod

#3703 Check guess tag and lexiqa languages not supported
  public/js/cat_source/es6/components/settingsPanel/Contents/EditorSettingsTab/GuessTag.js
  public/js/cat_source/es6/components/settingsPanel/Contents/EditorSettingsTab/Lexiqa.js
  public/js/cat_source/es6/utils/lxq.main.js
  public/js/cat_source/es6/utils/segmentUtils.js
Labels: Ready for prod

#3702 Xliff to target page - Fix
  public/js/cat_source/es6/components/xliffToTarget/UploadXliff.js
Labels: Ready for prod

#3681 Fixed trailing space QA check
  lib/Utils/LQA/QA.php
Labels: Ready for prod

#3676 Fixed job quality_overall when is_pass is null
  lib/Plugins/Features/ReviewExtended/ChunkReviewModel.php
  lib/Plugins/Features/ReviewExtended/Model/QualityReportModel.php
  lib/Utils/CatUtils.php
Labels: Ready for prod

#3675 Fix tag size when "Show whitespace characters" is active
  public/css/sass/components/segment/Tag.scss
Labels: Ready for prod

#3650 New welcome email
  lib/Utils/Email/WelcomeEmail.php
  lib/View/Emails/Signup/welcome_content.html
  lib/View/Emails/skeleton.html
Labels: Ready for prod
