Repository matecat/MateCat, pull requests merged in 2024-10, with the labels that each got.

#3576 Generate R2 endpoint docs
  public/api/swagger-source.js
Labels: Ready for prod

#3618 Sse message reload
  nodejs/server.js
  public/js/cat_source/es6/actions/UserActions.js
  public/js/cat_source/es6/components/common/ApplicationWrapper/ApplicationWrapper.js
  public/js/cat_source/es6/components/common/ApplicationWrapper/ForcedActionModal.js
  public/js/cat_source/es6/components/common/ApplicationWrapper/UserDisconnectedBox.js
  public/js/cat_source/es6/constants/UserConstants.js
  public/js/cat_source/es6/sse/SseListener.js
  public/js/cat_source/es6/stores/UserStore.js
Labels: Freddy

#3626 Sentry fix
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/components/createProject/TargetLanguagesSelect.js
  public/js/cat_source/es6/components/createProject/TmGlossarySelect.js
  public/js/cat_source/es6/components/header/ActionMenu.js
  public/js/cat_source/es6/components/header/cattol/segment_filter/segment_filter.js
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/tagUtils.js
  public/js/cat_source/es6/pages/NewProject.js
  public/js/cat_source/es6/stores/SegmentStore.js
  public/js/cat_source/es6/utils/speech2text.js
Labels: Ready for prod

#3627 Fix: removed email in comments
  lib/Controller/commentController.php
  lib/Model/Comments/BaseCommentStruct.php
Labels: Ready for prod, Freddy, HotFix

#3625 Fix: Engine not updated when id_tms changes from 1 to 0 or vice versa.
  lib/Utils/AsyncTasks/Workers/SetContributionMTWorker.php
  lib/Utils/AsyncTasks/Workers/SetContributionWorker.php
  tests/unit/TestContribution/SetContributionMTWorkerTest.php
  tests/unit/TestContribution/SetContributionWorkerTest.php
Labels: Ready for prod

#3604 Fix set key permissions as owner
  lib/Controller/updateJobKeysController.php
Labels: Ready for prod

#3629 Fix suggestion null
  lib/Controller/API/V3/SegmentAnalysisController.php
  lib/Model/EditLog/EditLogSegmentStruct.php
Labels: bug, Ready for prod, HotFix

#3630 Fixed null value for match type ( because of a previous bug )
  lib/Model/Analysis/AbstractStatus.php
Labels: bug, HotFix

#3635 HotFix: cache eviction issues
  lib/Model/Analysis/AnalysisDao.php
  lib/Model/Comments/CommentDao.php
  lib/Model/DataAccess/AbstractDao.php
  lib/Model/DataAccess/DaoCacheTrait.php
  lib/Model/EnginesModel/EngineDAO.php
  lib/Model/Filters/FiltersConfigTemplateDao.php
  lib/Model/Jobs/JobDao.php
  lib/Model/Jobs/MetadataDao.php
  lib/Model/LQA/ChunkReviewDao.php
  lib/Model/Outsource/ConfirmationDao.php
  lib/Model/OwnerFeatures/OwnerFeatureDao.php
  lib/Model/Pagination/Pager.php
  lib/Model/PayableRates/CustomPayableRateDao.php
  lib/Model/Projects/MetadataDao.php
  lib/Model/Projects/ProjectDao.php
  lib/Model/Projects/ProjectTemplateDao.php
  lib/Model/Segments/SegmentDao.php
  lib/Model/Teams/MembershipDao.php
  lib/Model/Teams/TeamDao.php
  lib/Model/Translators/JobsTranslatorsDao.php
  lib/Model/Users/MetadataDao.php
  lib/Model/Users/UserDao.php
  lib/Model/Xliff/XliffConfigTemplateDao.php
Labels: bug, Freddy, HotFix

#3646 Removed duplicated call to recount update-pass-fail procedure
  lib/Plugins/Features/AbstractRevisionFeature.php
  lib/Plugins/Features/ReviewExtended/BatchReviewProcessor.php
  lib/Plugins/Features/ReviewExtended/ChunkReviewModel.php
  lib/Plugins/Features/ReviewExtended/IChunkReviewModel.php
  lib/Utils/ProjectManager.php
Labels: bug, Freddy
