Repository matecat/MateCat, pull requests merged in 2024-06, with the labels that each got.

#3364 Fix context in setTranslation
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/components/segments/SegmentButtons.js
  public/js/cat_source/es6/components/segments/utils/translationMatches.js
  public/js/cat_source/es6/stores/SegmentStore.js
  public/js/cat_source/ui.segment.js
Labels: Ready for prod

#3362 Static stomp connections must not be used in daemons
  lib/Utils/ActivityLog/Activity.php
  lib/Utils/ProjectManager.php
  lib/Utils/WorkerClient.php
Labels: Ready for prod

#3353 Cattool page changed message when analysis is still progress
  public/js/cat_source/es6/components/modals/FatalErrorModal.js
  public/js/cat_source/es6/pages/CatTool.js
Labels: Freddy

#3368 Added `id_job` and `id_segment` to getGlossary
  lib/Controller/glossaryController.php
  lib/Utils/AsyncTasks/Workers/GlossaryWorker.php
  lib/Utils/Engines/MyMemory.php
Labels: Ready for prod

#3233 New language labels
  lib/Utils/Langs/Languages.php
  lib/Utils/Langs/supported_langs.json
Labels: Freddy, on Hold

#3371 Comments component check teams not defined
  public/js/cat_source/es6/components/segments/SegmentCommentsContainer.js
Labels: Ready for prod

#3375 Updated xliff-parser v2.1.1
  composer.lock
Labels: Ready for prod, Freddy

#3384 QR: segment status filter
  public/js/cat_source/es6/api/getQualityReportSegmentsFiles/getQualityReportSegmentsFiles.js
  public/js/cat_source/es6/components/quality_report/FilterSegments.js
Labels: Ready for prod

#3382 Fuzzy match state-qualifiers correct handling
  lib/Utils/Constants/XliffTranslationStatus.php
  lib/Utils/ProjectManager.php
Labels: Ready for prod

#3363 Split job raw
  lib/Controller/API/V2/JobSplitController.php
  lib/Controller/splitJobController.php
  lib/Utils/ProjectManager.php
  public/api/swagger-source.js
  public/css/sass/common-modals.scss
  public/css/sass/modals/split_modal.scss
  public/js/cat_source/es6/api/checkSplitRequest/checkSplitRequest.js
  public/js/cat_source/es6/api/confirmSplitRequest/confirmSplitRequest.js
  public/js/cat_source/es6/components/modals/SplitJob.js
  public/js/cat_source/es6/utils/queryString/queryString.js
Labels: Ready for prod

#3344 New cattol footer
  lib/Controller/catController.php
  lib/Controller/getSearchController.php
  lib/Controller/setTranslationController.php
  lib/Model/Translations/SegmentTranslationDao.php
  lib/Utils/CatUtils.php
  public/css/sass/cattool.scss
  public/css/sass/commons/_progress-mc-bar.scss
  public/css/sass/components/CattolFooter.scss
  public/css/sass/components/common/Tooltip.scss
  public/css/sass/main.scss
  public/css/sass/style.scss
  public/js/cat_source/es6/components/common/Tooltip.js
  public/js/cat_source/es6/components/footer/CattoolFooter.js
  public/js/cat_source/es6/components/footer/CattoolFooter.test.js
  public/js/cat_source/es6/components/icons/IconArrowRight.js
  public/js/cat_source/es6/components/icons/IconRedirect.js
  public/js/cat_source/es6/pages/CatTool.js
  public/js/cat_source/es6/stores/CatToolStore.js
Labels: Ready for prod

#3330 Replace calendar library
  jest.config.js
  package.json
  public/css/sass/commons/_outsource.scss
  public/js/cat_source/es6/components/outsource/AssignToTranslator.js
  public/js/cat_source/es6/components/outsource/OutsourceContainer.js
  public/js/cat_source/es6/components/outsource/OutsourceVendor.js
  public/js/cat_source/es6/utils/commonUtils.js
  public/js/lib/calendar.min.js
  webpack.config.js
  yarn.lock
Labels: Ready for prod

#3391 Fix comment textarea scrolling
  public/css/sass/mbc-style.scss
  public/js/cat_source/es6/components/segments/SegmentCommentsContainer.js
Labels: Ready for prod

#3397 Fix comments display date
  public/js/cat_source/es6/components/segments/SegmentCommentsContainer.js
Labels: Ready for prod

#3261 Removed advancement_wc logics
  lib/Model/WordCount/WordCounterDao.php
  lib/Plugins/Features/ReviewExtended/SegmentTranslationModel.php
Labels: Freddy

#3381 Fix v1/stats
  lib/Controller/API/V1/StatsController.php
  lib/Model/WordCount/WordCountStruct.php
Labels: bug, Freddy

#3400 Fix outsource
  lib/Utils/OutsourceTo/Translated.php
Labels: Ready for prod

#3390 Fix OCR language check
  composer.json
  lib/Controller/convertFileController.php
  lib/Controller/xliffToTargetController.php
  lib/Model/Conversion/ConvertedFileModel.php
  lib/Model/ConversionHandler.php
  lib/Utils/API/Upload.php
  lib/Utils/Filters/OCRCheck.php
  lib/Utils/Langs/Languages.php
  lib/Utils/Langs/supported_langs.json
  lib/Utils/MimeTypes/Constants/MimeTypesMap.php
  lib/Utils/MimeTypes/Guesser/FileBinaryMimeTypeGuesser.php
  lib/Utils/MimeTypes/Guesser/FileExtensionMimeTypeGuesser.php
  lib/Utils/MimeTypes/Guesser/FileinfoMimeTypeGuesser.php
  lib/Utils/MimeTypes/Guesser/MimeTypeGuesserInterface.php
  lib/Utils/MimeTypes/MimeTypes.php
  lib/Utils/ZipArchiveExtended.php
  lib/Utils/fileupload/upload.class.php
Labels: Freddy

#3398 Homepage select target more than one display number
  public/js/cat_source/es6/components/createProject/TargetLanguagesSelect.js
  public/js/cat_source/es6/pages/NewProject.js
Labels: Freddy

#3407 Handle convertFile API warnings
  public/css/sass/common.scss
  public/js/upload_main.js
Labels: Ready for prod

#3412 Fix comment json representation
  lib/Model/Comments/BaseCommentStruct.php
Labels: Ready for prod

#3402 Improved logging on set contribution worker
  lib/Utils/AsyncTasks/Workers/SetContributionMTWorker.php
  lib/Utils/AsyncTasks/Workers/SetContributionWorker.php
  lib/Utils/Engines/EngineInterface.php
  lib/Utils/Engines/MyMemory.php
Labels: Ready for prod, Freddy

#3414 Fix comment json representation
  lib/Model/Comments/BaseCommentStruct.php
Labels: Ready for prod

#3410 Emoji 1.0.6
  composer.lock
Labels: Ready for prod

#3419 Fixed mime type check for tmx
  lib/Utils/MimeTypes/Guesser/SimpleMarkupMimeTypeGuesser.php
Labels: Ready for prod, Freddy, HotFix

#3420 Improved check
  lib/Utils/MimeTypes/Guesser/SimpleMarkupMimeTypeGuesser.php
Labels: Ready for prod

#3422 Send segmentation rule in convertFile API
  public/js/cat_source/es6/pages/NewProject.js
Labels: Freddy

#3421 Fix tmkey from query string
  public/js/cat_source/es6/pages/NewProject.js
Labels: Ready for prod
