Repository matecat/MateCat, pull requests merged in 2024-09, with the labels that each got.

#3546 Securing team members public API
  lib/Controller/API/Commons/Validators/TeamAccessValidator.php
  lib/Controller/catController.php
  lib/Model/Teams/MembershipDao.php
  lib/Routes/utils_routes.php
  lib/View/templates/_index.html
  public/js/cat_source/es6/api/getTeamUsers/getTeamUsers.js
  public/js/cat_source/es6/components/header/cattol/CommentsButton.js
Labels: Ready for prod

#3541 Sentry fix issue MATECAT-42A
  public/js/cat_source/es6/utils/commonUtils.js
Labels: Ready for prod

#3539 Xliff parser 2.2.6
  composer.lock
Labels: Ready for prod

#3451 Show matesub alert in upload page
  public/css/sass/notifications.scss
  public/js/cat_source/es6/components/modals/LoginModal.js
  public/js/cat_source/es6/components/notificationsComponent/NotificationItem.js
  public/js/cat_source/es6/components/quality_report/QualityReport.js
  public/js/cat_source/es6/pages/AnalyzePage.js
  public/js/cat_source/es6/pages/CatTool.js
  public/js/cat_source/es6/pages/NewProject.js
  public/js/cat_source/es6/utils/commonUtils.js
  public/js/upload_main.js
Labels: Ready for prod, Plugin Dependencies

#3542 [Security] Fix: URL Redirection on Forgot Password
  lib/Model/Users/SignupModel.php
Labels: Ready for prod

#3502 Fixed wrong tag mismatch detection in download
  composer.lock
  lib/Controller/downloadFileController.php
Labels: Ready for prod

#3540 [Security] Fix: URL Redirection on Registering New User
  lib/Model/Users/SignupModel.php
Labels: Ready for prod

#3553 Xliff parser 2.2.7
  composer.lock
Labels: Ready for prod

#3562 Sentry fix
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/components/analyze/AnalyzeMain.js
  public/js/cat_source/es6/components/analyze/ChunkAnalyze.js
  public/js/cat_source/es6/components/header/cattol/segment_filter/segment_filter.js
  public/js/cat_source/es6/components/modals/ModalWindow.js
  public/js/cat_source/es6/components/segments/Segment.js
  public/js/cat_source/es6/components/segments/SegmentButtons.js
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/tagUtils.js
  public/js/cat_source/es6/pages/CatTool.js
  public/js/cat_source/es6/pages/NewProject.js
  public/js/cat_source/es6/utils/speech2text.js
Labels: Ready for prod

#3570 Fix glossary check
  lib/Controller/API/App/GlossaryController.php
Labels: Ready for prod

#3567 Xliff parser 2.2.8
  composer.lock
Labels: Ready for prod

#3566 Query analysis data from master database
  lib/Utils/Analysis/Workers/TMAnalysisWorker.php
Labels: Ready for prod

#3571 Subfiltering v2.2.5
  composer.lock
Labels: Ready for prod

#3577 Fix opening settings job without MT
  public/js/cat_source/es6/pages/CatTool.js
Labels: Ready for prod

#3564 Standardize UI tooltip
  public/css/sass/commons/_aria-label-tooltip.scss
  public/css/sass/components/common/LabelWithTooltip.scss
  public/css/sass/components/common/Tooltip.scss
  public/js/cat_source/es6/components/segments/SegmentFooterTabGlossary/GlossaryItem.js
Labels: Ready for prod

#3555 Avoid entering null values in the username field
  public/js/cat_source/es6/components/modals/PreferencesModal.js
Labels: Ready for prod

#3556 Update setting panel urls
  public/js/cat_source/es6/components/settingsPanel/SettingsPanel.js
Labels: Ready for prod

#3561 Fix open settings panel - set active incorrect segment footer tab
  public/js/cat_source/es6/components/segments/SegmentFooter.js
  public/js/cat_source/es6/components/settingsPanel/Contents/AdvancedOptionsTab/CrossLanguagesMatches.js
Labels: Ready for prod

#3583 Fixed wrong drive client initialization
  lib/Controller/ConnectedServices/GDrive/GDriveController.php
  lib/Decorator/CatDecorator.php
  lib/Utils/ConnectedServices/GDrive/Session.php
  lib/Utils/ProjectManager.php
Labels: Ready for prod

#3585 Sentry fix
  public/js/cat_source/es6/components/createProject/TargetLanguagesSelect.js
  public/js/cat_source/es6/components/languageSelector/LanguageSelector.js
Labels: Ready for prod

#3586 Httponly on session cookie
  inc/Bootstrap.php
Labels: Ready for prod, Freddy

#3579 Fix glossary check
  lib/Controller/API/App/GlossaryController.php
  public/js/cat_source/es6/components/segments/Editarea.js
Labels: Ready for prod

#3448 Avoid sending suggestion array in revise
  public/js/cat_source/es6/utils/segmentUtils.js
Labels: Ready for prod

#3563 File Upload - Empty files validation
  lib/Utils/API/Upload.php
  lib/View/fileupload/upload.class.php
Labels: Ready for prod
