Repository matecat/MateCat, pull requests merged in 2024-01, with the labels that each got.

#3084 Fix emoji
  composer.lock
Labels: Ready for prod

#3020 [Segment translations] Avoid saving `version_number` null
  lib/Controller/API/V2/SegmentTranslationIssueController.php
  lib/Model/ProjectManager/ProjectManagerModel.php
  lib/Model/Translations/SegmentTranslationDao.php
  lib/Model/Translations/SegmentTranslationStruct.php
  lib/Plugins/Features/TranslationVersions/Handlers/TranslationVersionsHandler.php
  lib/Plugins/Features/TranslationVersions/Model/TranslationEvent.php
  lib/Utils/ProjectManager.php
Labels: Ready for prod

#3025 Fix `getPasswordsMap` query
  lib/Model/Projects/ProjectDao.php
Labels: Ready for prod

#3033 Fix MT deletion by user
  lib/Utils/TmKeyManagement/TmKeyManagement.php
Labels: Ready for prod

#3086 [MMT] check account
  lib/Plugins/Features/Mmt.php
Labels: Ready for prod

#3091 Languages update
  lib/Utils/Langs/supported_langs.json
Labels: Ready for prod, Freddy

#3089 No private keys message
  public/css/sass/upload-page.scss
  public/js/cat_source/es6/components/createProject/TmGlossarySelect.js
Labels: Ready for prod

#3083 Tooltip message case sensitive ModernMT glossary
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MTGlossary.js
Labels: Ready for prod

#3073 Fix RTL entity delete from keyboard
  public/js/cat_source/es6/components/segments/Editarea.js
Labels: Ready for prod

#3038 Tab Messages: hide empty tab
  public/js/cat_source/es6/components/segments/SegmentFooter.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabMessages.js
Labels: Ready for prod

#3090 Fix regex of function restoreTempTags
  public/js/cat_source/es6/utils/textUtils.js
Labels: Ready for prod

#3096 Chars counter html unescape
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/tagUtils.js
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/textUtils.js
Labels: Ready for prod

#3081 Fix tags not displaying closed segments
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/tagUtils.js
Labels: Ready for prod

#3093 MT creation disable submit button pending request
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MachineTranslationTab.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MtEngines/AltLang.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MtEngines/Apertium.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MtEngines/GoogleTranslate.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MtEngines/Intento.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MtEngines/MicrosoftHub.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MtEngines/ModernMt.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MtEngines/SmartMate.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MtEngines/Yandex.js
Labels: Ready for prod

#3108 Fixed Balkan Gipsy code
  lib/Utils/Langs/supported_langs.json
Labels: Ready for prod

#3101 [API] Added the key value of new memory created on MM
  lib/Controller/API/V3/MyMemoryController.php
Labels: Ready for prod

#3099 Fix htaccess
  .htaccess
Labels: Ready for prod

#3092 [Xliff parser] - fix counts
  composer.lock
Labels: Ready for prod

#3088 Update suggestions
  lib/Controller/deleteContributionController.php
  lib/Controller/setTranslationController.php
  lib/Model/Translations/SegmentTranslationDao.php
  lib/Utils/Analysis/Workers/TMAnalysisWorker.php
  lib/Utils/AsyncTasks/Workers/GetContributionWorker.php
  public/js/cat_source/es6/api/deleteContribution/deleteContribution.js
  public/js/cat_source/es6/components/segments/utils/translationMatches.js
Labels: Ready for prod

#3097 [API] Fix Error handling
  lib/Controller/API/V2/ProjectCreationStatusController.php
  lib/Controller/getProjectsController.php
  lib/View/API/V2/Json/Error.php
  router.php
Labels: Ready for prod

#3109 Fix Deepl
  lib/Utils/AsyncTasks/Workers/GetContributionWorker.php
Labels: Ready for prod, HotFix

#3085 New alias routes for download files
  lib/Controller/API/V2/AbstractDownloadController.php
  lib/Controller/API/V2/DownloadFileController.php
  lib/Controller/API/V2/ExportTMXController.php
  lib/Routes/api_v2_routes.php
  lib/Routes/utils_routes.php
Labels: Ready for prod

#3122 Send translation suggestion index
  lib/Controller/setTranslationController.php
  lib/Model/Translations/SegmentTranslationDao.php
  public/js/cat_source/ui.core.js
Labels: Ready for prod

#3031 Preserve ICE fuzzy band
  lib/Utils/Analysis/Workers/TMAnalysisWorker.php
Labels: Ready for prod
