Repository matecat/MateCat, pull requests merged in 2024-04, with the labels that each got.

#3234 fix corrupted intermediate XLIFF download
  lib/Controller/API/V2/DownloadFileController.php
Labels: Ready for prod

#3229 MT: hide glossy options for no owners user
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MachineTranslationTab.js
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TranslationMemoryGlossaryTab.js
Labels: Ready for prod

#3196 MMT glossary import fix
  lib/Controller/API/V3/ModernMTController.php
  public/js/cat_source/es6/api/createMemoryAndImportGlossary/createMemoryAndImportGlossary.js
  public/js/cat_source/es6/api/importMemoryGlossary/importMemoryGlossary.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MTGlossary/MTGlossaryCreateRow.js
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MTGlossary/MTGlossaryRow.js
Labels: Ready for prod

#2917 [MMT] Add `client_id` param to MyMemory calls
  lib/Controller/getContributionController.php
  lib/Controller/setTranslationController.php
  lib/Model/Jobs/JobDao.php
  lib/Utils/AsyncTasks/Workers/SetContributionMTWorker.php
  lib/Utils/AsyncTasks/Workers/SetContributionWorker.php
  lib/Utils/Engines/MyMemory.php
Labels: Freddy, on Hold

#3206 Add new engine fix
  lib/Controller/engineController.php
Labels: Ready for prod

#3275 Homepage fix errors and warnings messages
  lib/View/templates/_upload.html
  public/css/sass/upload-page.scss
  public/js/cat_source/es6/pages/NewProject.js
  public/js/gdrive.upload.js
  public/js/upload_main.js
Labels: Ready for prod

#3278 Fixed count on progress estimation
  lib/Model/Translations/SegmentTranslationDao.php
  public/js/cat_source/es6/components/footer/CattoolFooter.js
Labels: Freddy

#3286 Used yarn version to drive versioning
  package.json
Labels: Freddy
