Repository matecat/MateCat, pull requests merged in 2025-03, with the labels that each got.

#3845 Fix exception when a job is deleted
  lib/Controller/copyAllSource2TargetController.php
  lib/Plugins/Features/TranslationEvents/Model/TranslationEvent.php
  lib/Utils/AsyncTasks/Workers/BulkSegmentStatusChangeWorker.php
  lib/Utils/TaskRunner/Exceptions/EndQueueException.php
Labels: Ready for prod

#3847 Fix TQMT
  public/js/cat_source/es6/components/segments/SegmentHeader.js
  public/js/cat_source/es6/components/segments/utils/translationMatches.js
Labels: Ready for prod

#3855 Authorization Bearer support
  .htaccess
  lib/Controller/API/Commons/Authentication/AuthenticationTrait.php
  lib/Controller/API/Commons/KleinController.php
  lib/Controller/API/NewController.php
  lib/Controller/AbstractControllers/ajaxController.php
Labels: Ready for prod

#3849 Remove tags button: hide when no tags in target
  public/js/cat_source/es6/components/segments/SegmentTarget.js
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/tagUtils.js
Labels: Ready for prod

#3831 Allow CDATA
  lib/Utils/CatUtils.php
Labels: Ready for prod

#3801 Comment fullName refactoring
  lib/Model/Comments/BaseCommentStruct.php
  lib/Model/Comments/CommentStruct.php
  lib/Utils/Email/BaseCommentEmail.php
  public/js/cat_source/es6/components/segments/SegmentCommentsContainer.js
Labels: Ready for prod

#3774 Avoid insert file with blank filename
  lib/Model/FilesStorage/AbstractFilesStorage.php
  lib/Utils/ProjectManager.php
Labels: Ready for prod

#3813 /api/v2/projects/{id_project}/{password}/r2 docs
  public/api/swagger-source.js
Labels: Ready for prod

#3858 Fixed crash on ioredis.quit()
  nodejs/src/Application.js
Labels: Ready for prod, Freddy

#3857 Fix: link in segment notes
  public/js/cat_source/es6/components/segments/SegmentFooterTabMessages.js
Labels: Ready for prod

#3860 Notifications: avoid displaying duplicate notifications
  public/js/cat_source/es6/sse/SocketListener.js
Labels: Ready for prod

#3864 Add shortcut: add remove tags
  public/css/sass/common-modals.scss
  public/js/cat_source/es6/components/segments/SegmentTarget.js
  public/js/cat_source/es6/utils/shortcuts.js
Labels: Ready for prod

#3797 Adding `dialect_strict` to Project templates
  inc/validation/schema/project_template.json
  lib/Model/Projects/ProjectTemplateDao.php
  lib/Model/Projects/ProjectTemplateStruct.php
  migrations/20250127143100_add_dialect_strict_to_project_templates.php
  public/css/sass/components/settingsPanel/TranslationMemoryGlossaryTab.scss
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TranslationMemoryGlossaryTab.js
  public/js/cat_source/es6/hooks/useProjectTemplates.js
  public/js/cat_source/es6/pages/NewProject.js
Labels: Ready for prod, Migration needed

#3866 Change link matching strict
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TranslationMemoryGlossaryTab.js
Labels: Ready for prod

#3856 Change project name
  lib/Controller/API/V2/ChangeProjectNameController.php
  lib/Model/Projects/ProjectDao.php
  lib/Routes/api_v2_routes.php
  lib/Routes/utils_routes.php
  lib/Utils/ProjectManager.php
  lib/Utils/Utils.php
  public/css/sass/commons/_manage.scss
  public/css/sass/components/UserProjectDropdown.scss
  public/js/cat_source/es6/actions/ManageActions.js
  public/js/cat_source/es6/api/changeProjectName/changeProjectName.js
  public/js/cat_source/es6/components/projects/ProjectContainer.js
  public/js/cat_source/es6/stores/ProjectsStore.js
Labels: Ready for prod

#3872 Added docs to new endpoint to change project name
  public/api/swagger-source.js
Labels: Ready for prod

#3870 Fix lexiqa report
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/components/header/cattol/segment_filter/segment_filter.js
  public/js/cat_source/es6/components/segments/utils/translationMatches.js
  public/js/cat_source/es6/pages/CatTool.js
  public/js/cat_source/es6/utils/lxq.main.js
  public/js/cat_source/es6/utils/speech2text.js
  public/js/cat_source/ui.core.js
Labels: Freddy

#3875 Segment `internal_id`
  lib/Model/Segments/SegmentDao.php
Labels: Ready for prod
