Repository matecat/MateCat, pull requests merged in 2025-07, with the labels that each got.

#3985 Create job keys with an invalid key
  lib/Controller/API/App/UserKeysController.php
  public/js/cat_source/es6/api/createNewTmKey/createNewTmKey.js
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TMCreateResourceRow.js
Labels: Ready for prod

#3963 Removed unused parames from projects creation
  lib/Controller/API/App/CreateProjectController.php
  lib/Controller/API/V1/NewController.php
  lib/Utils/ProjectManager.php
  public/api/swagger-source.js
Labels: Freddy

#4014 Fix: css analyze
  public/css/sass/components/Analyze/JobAnalyze.scss
Labels: Ready for prod

#4010 Refactoring accordion job instructions
  public/css/sass/modals/instructionsModal.scss
  public/js/components/modals/JobMetadataModal.js
Labels: Ready for prod

#4016 Set right icon yaml file
  public/js/utils/commonUtils.js
Labels: Ready for prod

#4012 Fix add/remove decorators
  public/js/components/segments/Editarea.js
Labels: Ready for prod

#4003 Fix tm keys
  public/js/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/ShareResource.js
  public/js/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TMCreateResourceRow.js
  public/js/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TMKeyRow.js
Labels: Ready for prod

#3979 Payable rates 2025
  lib/Model/Analysis/PayableRates.php
  tests/unit/Model/PayableRatesTest.php
Labels: Ready for prod

#3975 Fix linefeed view with whitespaces enabled
  public/js/components/segments/utils/DraftMatecatUtils/tagModel.js
Labels: Ready for prod

#3998 Adding new params to `api/app/new-project` and `api/app/convert-file`
  inc/validation/schema/filters_extraction_parameters.json
  inc/validation/schema/payable_rate.json
  inc/validation/schema/xliff_parameters_rules_wrapper.json
  lib/Controller/API/App/ConvertFileController.php
  lib/Controller/API/App/CreateProjectController.php
  lib/Controller/ConnectedServices/GDrive/GDriveController.php
  lib/Model/Conversion/ConversionHandler.php
  lib/Model/FeatureSet.php
  lib/Routes/gdrive_routes.php
  lib/Utils/ProjectManager.php
  public/js/api/convertFileRequest/convertFileRequest.js
  public/js/api/openGDriveFiles/openGDriveFiles.js
  public/js/components/createProject/UploadFileLocal.js
  public/js/components/createProject/UploadGdrive.js
  public/js/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TMCreateResourceRow.js
  public/js/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TMKeyRow.js
  public/js/components/settingsPanel/SettingsPanel.js
  public/js/pages/NewProject.js
Labels: Ready for prod

#4027 Fix mt contexts
  lib/Controller/API/App/GetContributionController.php
  lib/Controller/API/App/SetTranslationController.php
Labels: HotFix

#4028 Missing emoji
  composer.lock
Labels: Ready for prod

#3987 Fix `owner` value in job keys API
  lib/Controller/API/App/TmKeyManagementController.php
Labels: Ready for prod

#3976 Correct `MT` enum as Xliff match type
  inc/validation/schema/xliff_parameters_rules_content.json
  public/js/components/settingsPanel/Contents/defaultTemplates/xliffOptions.json
Labels: Ready for prod
