Repository matecat/MateCat, pull requests merged in 2025-05, with the labels that each got.

#3925 Fix upload zip files
  lib/Controller/API/App/ConvertFileController.php
  lib/Utils/API/ConvertFile.php
Labels: Ready for prod

#3924 Fix download analysis
  lib/Controller/API/App/DownloadAnalysisReportController.php
Labels: Ready for prod

#3923 Sentry fix: gapi not defined
  lib/View/templates/_upload.html
  public/js/cat_source/es6/components/createProject/UploadGdrive.js
  public/js/cat_source/es6/pages/NewProject.js
Labels: Ready for prod, Freddy, Merged Freddy

#3918 Fix: cursor position after deleting an entity that precedes another
  public/js/cat_source/es6/components/segments/Editarea.js
Labels: Ready for prod

#3910 Download QR in a single file
  lib/Controller/API/V3/DownloadQRController.php
Labels: Ready for prod

#3906 Fix term details with multiple editor blocks
  public/js/cat_source/es6/components/segments/GlossaryComponents/GlossaryHighlight.component.js
  public/js/cat_source/es6/components/segments/GlossaryComponents/QaCheckBlacklistHighlight.component.js
  public/js/cat_source/es6/components/segments/GlossaryComponents/QaCheckGlossaryHighlight.component.js
Labels: Ready for prod

#3905 Fix character counter
  public/js/cat_source/es6/components/segments/utils/DraftMatecatUtils/textUtils.js
Labels: Ready for prod

#3903 `stripTagsPreservingHrefs` improvement
  lib/Utils/Utils.php
  tests/unit/Utils/StripTagsPreservingHrefsTest.php
Labels: Ready for prod

#3901 Fix: activating / deactivating lexiqa
  public/js/cat_source/es6/utils/lxq.main.js
Labels: Ready for prod

#3900 Update shortcuts labels
  public/js/cat_source/es6/components/header/cattol/SearchButton.js
  public/js/cat_source/es6/components/header/cattol/SettingsButton.js
  public/js/cat_source/es6/components/segments/Segment.js
  public/js/cat_source/es6/components/segments/SegmentTarget.js
  public/js/cat_source/es6/components/segments/SegmentsContainer.js
Labels: Ready for prod

#3915 QR: add analysis match type info
  public/css/sass/components/pages/QualityReportPage.scss
  public/js/cat_source/es6/components/quality_report/SegmentQR.js
  public/js/cat_source/es6/components/quality_report/SegmentQRLine.js
  public/js/cat_source/es6/constants/Constants.js
Labels: Ready for prod

#3902 Fix download QR in XML
  lib/Controller/API/V3/DownloadQRController.php
Labels: Ready for prod

#3929 Sentry fix
  public/css/sass/components/pages/NewProjectPage.scss
  public/js/cat_source/es6/components/createProject/UploadFile.js
  public/js/cat_source/es6/components/header/ActionMenu.js
  public/js/cat_source/es6/components/header/cattol/search/Search.js
  public/js/cat_source/es6/components/header/cattol/segment_filter/segment_filter.js
  public/js/cat_source/es6/components/onBoarding/OnBoarding.js
  public/js/cat_source/es6/components/projects/ProjectContainer.js
  public/js/cat_source/es6/components/segments/GlossaryComponents/QaCheckBlacklistHighlight.component.js
  public/js/cat_source/es6/components/segments/GlossaryComponents/QaCheckGlossaryHighlight.component.js
  public/js/cat_source/es6/components/segments/Segment.js
  public/js/cat_source/es6/components/segments/SegmentButtons.js
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/ImportTMX.js
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/hooks/useImport.js
Labels: Ready for prod, Freddy
