Repository matecat/MateCat, pull requests merged in 2025-02, with the labels that each got.

#3805 Update lara copy
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MtEngines/Lara.js
Labels: Ready for prod, Freddy

#3794 Adding Spanish variants
  lib/Utils/Langs/supported_langs.json
Labels: Ready for prod, Freddy

#3791 Shared key email
  lib/View/Emails/ShareKey/message_content.html
Labels: Ready for prod, Freddy

#3785 Delete single severity from category QF template
  inc/validation/schema/qa_model.json
  lib/Model/LQA/CategoryDao.php
  lib/Model/QAModelTemplate/QAModelTemplateCategoryStruct.php
  lib/Model/QAModelTemplate/QAModelTemplateDao.php
  lib/Model/QAModelTemplate/QAModelTemplateSeverityStruct.php
  lib/Model/QAModelTemplate/QAModelTemplateStruct.php
  public/css/sass/components/settingsPanel/QualityFrameworkTab.scss
  public/js/cat_source/es6/components/common/Tooltip.js
  public/js/cat_source/es6/components/quality_report/QualitySummaryTable.js
  public/js/cat_source/es6/components/settingsPanel/Contents/QualityFrameworkTab/AddSeverity.js
  public/js/cat_source/es6/components/settingsPanel/Contents/QualityFrameworkTab/AddSeverityCell.js
  public/js/cat_source/es6/components/settingsPanel/Contents/QualityFrameworkTab/CategoriesSeveritiesTable.js
  public/js/cat_source/es6/components/settingsPanel/Contents/QualityFrameworkTab/ModifySeverity.js
  public/js/cat_source/es6/components/settingsPanel/Contents/QualityFrameworkTab/SeverityColumn.js
  public/js/cat_source/es6/components/settingsPanel/Contents/QualityFrameworkTab/SeverityRow.js
  public/mocks/qaModelTemplateMocks.js
Labels: Ready for prod

#3811 Fix tooltip overflow segment component
  public/css/sass/components/common/Tooltip.scss
  public/css/sass/lexiqa.scss
  public/js/cat_source/es6/components/common/Tooltip.js
  public/js/cat_source/es6/components/segments/GlossaryComponents/GlossaryHighlight.component.js
  public/js/cat_source/es6/components/segments/GlossaryComponents/QaCheckBlacklistHighlight.component.js
  public/js/cat_source/es6/components/segments/GlossaryComponents/QaCheckGlossaryHighlight.component.js
  public/js/cat_source/es6/components/segments/LexiqaHighlight/LexiqaHighlight.component.js
  public/js/cat_source/es6/components/segments/TagEntity/TagEntity.component.js
  public/js/cat_source/es6/components/settingsPanel/Contents/QualityFrameworkTab/SeverityRow.js
Labels: Ready for prod

#3819 Added new querystring param `engineId` - Open specific form to add MT
  public/js/cat_source/es6/components/settingsPanel/Contents/MachineTranslationTab/MachineTranslationTab.js
Labels: Freddy

#3821 Fix segment analysis query
  lib/Model/Segments/SegmentDao.php
Labels: Ready for prod

#3781 Set max limit of TM keys to 10
  lib/Controller/API/NewController.php
Labels: Ready for prod, Freddy

#3780 Subfiltering 2.2.7
  composer.lock
Labels: Ready for prod, Freddy

#3776 Removed /api/v2/project-completion-status/[i:id_project]
  lib/Controller/API/V2/ProjectCompletionStatus.php
  lib/Routes/api_v2_routes.php
Labels: Ready for prod, Freddy

#3834 Fixed total tte for job
  lib/Controller/setTranslationController.php
Labels: Ready for prod, Freddy

#3832 Sentry fix MATECAT-4AN
  public/js/cat_source/es6/actions/CatToolActions.js
  public/js/cat_source/es6/components/analyze/AnalyzeChunksResume.js
  public/js/cat_source/es6/components/common/Tooltip.js
  public/js/cat_source/es6/components/projects/ProjectContainer.js
  public/js/cat_source/es6/components/segments/SegmentTarget.js
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TMCreateResourceRow.js
Labels: Ready for prod

#3829 Fixed filter option for match 100%
  lib/Controller/API/V2/SegmentTranslationIssueController.php
  lib/Plugins/Features/SegmentFilter/Model/SegmentFilterDao.php
Labels: Ready for prod, Freddy

#3825 Publish Top quality MT in UI matches
  lib/Plugins/Features/Mmt.php
  lib/Utils/AsyncTasks/Workers/GetContributionWorker.php
  public/js/cat_source/es6/components/segments/SegmentFooterTabMatches.js
  public/js/cat_source/es6/components/segments/utils/translationMatches.js
Labels: Ready for prod, Freddy

#3824 Industry word count should contains also ICE_MT
  lib/Model/Analysis/AbstractStatus.php
  lib/Utils/Analysis/Workers/TMAnalysisWorker.php
Labels: Ready for prod, Freddy

#3839 Reverted ProjectCompletionStatus deletion
  lib/Controller/API/V2/ProjectCompletionStatus.php
Labels: Ready for prod
