Repository matecat/MateCat, pull requests merged in 2025-01, with the labels that each got.

#3748 Avoid empty users first_name and last_name
  lib/Controller/API/App/Authentication/SignupController.php
  lib/Controller/API/V2/UserController.php
  lib/Model/Users/Authentication/SignupModel.php
  lib/Model/Users/UserDao.php
  lib/Utils/CatUtils.php
Labels: Ready for prod

#3747 Adding comments to QA Reports
  lib/Controller/API/V3/DownloadQRController.php
Labels: Ready for prod

#3746 Fix tooltip label shortcut translated button
  public/js/cat_source/es6/components/segments/SegmentButtons.js
  public/js/cat_source/es6/components/segments/SegmentPlaceholderLite.js
  public/js/cat_source/es6/components/segments/SegmentsContainer.js
  public/js/cat_source/es6/components/settingsPanel/Contents/FileImportTab/FiltersParams/MsWord.js
Labels: Ready for prod

#3731 Relax filters on key description
  lib/Controller/userKeysController.php
Labels: Ready for prod

#3727 Dropdown fix: qr and cattool page
  public/css/sass/style.scss
  public/js/cat_source/es6/pages/QualityReport.js
Labels: Ready for prod

#3723 Correct Matecat name in system email
  inc/INIT.php
  lib/Controller/API/V2/DownloadFileController.php
  lib/Controller/downloadFileController.php
  lib/Decorator/ActivityLogDecorator.php
  lib/Model/ConversionHandler.php
  lib/Model/Features.php
  lib/Plugins/Features/ReviewExtended/ReviewedWordCountModel.php
  lib/Utils/AsyncTasks/Workers/ErrMailWorker.php
  lib/Utils/AsyncTasks/Workers/MailWorker.php
  lib/Utils/Email/AbstractEmail.php
  lib/Utils/Email/BaseCommentEmail.php
  lib/Utils/Email/InvitedToTeamEmail.php
  lib/Utils/Email/SendToTranslatorAbstract.php
  lib/Utils/Email/SendToTranslatorForDeliveryChangeEmail.php
  lib/Utils/Email/SendToTranslatorForJobSplitEmail.php
  lib/Utils/Email/SendToTranslatorForNewJobEmail.php
  lib/Utils/Email/SignupEmail.php
  lib/Utils/Filters.php
  lib/Utils/Log.php
  lib/Utils/OutsourceTo/AbstractProvider.php
  lib/Utils/ProjectManager.php
  lib/Utils/TmKeyManagement/ShareKeyEmail.php
  lib/Utils/Utils.php
  lib/View/Emails/Comment/action_on_a_comment.html
  lib/View/Emails/Revise/second_pass_segment_changed_notice.html
  lib/View/templates/_index.html
  lib/View/templates/_manage.html
Labels: Ready for prod

#3712 Restored API login validation
  lib/Controller/API/Commons/Validators/LoginValidator.php
Labels: Ready for prod

#3708 Sentry MATECAT-3XX
  public/js/cat_source/es6/components/createProject/SourceLanguageSelect.js
  public/js/cat_source/es6/components/createProject/TargetLanguagesSelect.js
  public/js/cat_source/es6/pages/NewProject.js
Labels: Ready for prod

#3754 Fix DeepL (missing project_id)
  lib/Utils/Analysis/Workers/FastAnalysis.php
  lib/Utils/Analysis/Workers/TMAnalysisWorker.php
Labels: HotFix

#3755 Fix deepl
  lib/Utils/Analysis/Workers/FastAnalysis.php
  lib/Utils/Analysis/Workers/TMAnalysisWorker.php
  lib/Utils/AsyncTasks/Workers/GetContributionWorker.php
  lib/Utils/Engines/DeepL.php
Labels: HotFix

#3758 Fix: cattool menu css
  public/css/sass/style.scss
Labels: Ready for prod

#3757 Fix: duplicate calls to getContributions
  inc/task_manager_config.ini.sample
  public/js/cat_source/es6/actions/CatToolActions.js
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabGlossary/SegmentFooterTabGlossary.js
  public/js/cat_source/es6/components/segments/utils/translationMatches.js
  public/js/cat_source/es6/components/settingsPanel/Contents/EditorSettingsTab/CrossLanguagesMatches.js
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TMKeyRow.js
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TranslationMemoryGlossaryTab.js
  public/js/cat_source/es6/constants/CatToolConstants.js
  public/js/cat_source/es6/constants/Constants.js
  public/js/cat_source/es6/stores/CatToolStore.js
Labels: Ready for prod

#3761 System email fix
  lib/Utils/Email/BaseCommentEmail.php
  lib/View/Emails/ShareKey/message_content.html
Labels: Ready for prod

#3752 Share key email message
  lib/View/Emails/ShareKey/message_content.html
Labels: Ready for prod

#3759 Added `dita` and `ditamap` formats
  inc/INIT.php
  inc/validation/schema/filters_extraction_parameters.json
  lib/Model/ConversionHandler.php
  lib/Model/Filters/DTO/Dita.php
  lib/Model/Filters/FiltersConfigTemplateDao.php
  lib/Model/Filters/FiltersConfigTemplateStruct.php
  migrations/20250110104800_add_dita_to_filters_config_table.php
  public/js/cat_source/es6/components/settingsPanel/Contents/FileImportTab/FiltersParams/AccordionGroupFiltersParams.js
  public/js/cat_source/es6/components/settingsPanel/Contents/FileImportTab/FiltersParams/Dita.js
  public/js/cat_source/es6/components/settingsPanel/Contents/FileImportTab/FiltersParams/FiltersParams.js
  public/js/cat_source/es6/components/settingsPanel/Contents/FileImportTab/XliffSettings/Xliff12.js
  public/js/cat_source/es6/components/settingsPanel/Contents/FileImportTab/XliffSettings/Xliff20.js
  public/js/cat_source/es6/components/settingsPanel/Contents/FileImportTab/XliffSettings/XliffSettings.js
  public/js/cat_source/es6/components/settingsPanel/Contents/SubTemplates/SubTemplateMoreMenu.js
  public/js/cat_source/es6/components/settingsPanel/Contents/defaultTemplates/filterParams.json
Labels: Ready for prod

#3704 Introduced prioritization and penalties for TM keys
  inc/validation/schema/job_keys.json
  inc/validation/schema/private_tm_key_json.json
  inc/validation/schema/project_template.json
  lib/Controller/API/App/TmKeyManagementController.php
  lib/Controller/API/NewController.php
  lib/Controller/API/V3/MetaDataController.php
  lib/Controller/createProjectController.php
  lib/Controller/getContributionController.php
  lib/Controller/updateJobKeysController.php
  lib/Model/Jobs/JobStruct.php
  lib/Model/Jobs/MetadataDao.php
  lib/Model/Projects/ProjectTemplateDao.php
  lib/Model/Projects/ProjectTemplateStruct.php
  lib/Utils/Analysis/Workers/FastAnalysis.php
  lib/Utils/Analysis/Workers/TMAnalysisWorker.php
  lib/Utils/AsyncTasks/Workers/GetContributionWorker.php
  lib/Utils/Contribution/ContributionRequestStruct.php
  lib/Utils/Engines/MyMemory.php
  lib/Utils/Engines/Results/MyMemory/Matches.php
  lib/Utils/ProjectManager.php
  lib/Utils/TmKeyManagement/TmKeyManagement.php
  lib/Utils/TmKeyManagement/TmKeyStruct.php
  migrations/20241203143100_add_mt_prioritization_to_project_templates.php
  public/css/sass/common-components.scss
  public/css/sass/components/common/NumericStepper.scss
  public/css/sass/components/settingsPanel/SettingsPanelTable.scss
  public/css/sass/components/settingsPanel/TranslationMemoryGlossaryTab.scss
  public/css/sass/style.scss
  public/js/cat_source/es6/api/updateJobKeys/updateJobKeys.js
  public/js/cat_source/es6/api/updateTmKey/updateTmKey.js
  public/js/cat_source/es6/components/common/MenuButton/MenuButton.js
  public/js/cat_source/es6/components/common/NumericStepper/NumericStepper.js
  public/js/cat_source/es6/components/common/NumericStepper/index.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabMatches.js
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TMCreateResourceRow.js
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TMKeyRow.js
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TmPrioritization.js
  public/js/cat_source/es6/components/settingsPanel/Contents/TranslationMemoryGlossaryTab/TranslationMemoryGlossaryTab.js
  public/js/cat_source/es6/components/settingsPanel/SettingsPanel.js
  public/js/cat_source/es6/components/settingsPanel/SettingsPanelTable/SettingsPanelRow.js
  public/js/cat_source/es6/components/settingsPanel/SettingsPanelTable/SettingsPanelTable.js
  public/js/cat_source/es6/hooks/useProjectTemplates.js
  public/js/cat_source/es6/pages/CatTool.js
  public/js/cat_source/es6/pages/NewProject.js
  tests/unit/TestMyMemory/GetMyMemoryTest.php
Labels: Ready for prod

#3771 Update footer links
  public/js/cat_source/es6/components/footer/Footer.js
Labels: Freddy

#3765 User create and edit fixes
  lib/Controller/API/App/Authentication/SignupController.php
  lib/Controller/API/V2/UserController.php
  lib/Utils/CatUtils.php
Labels: Ready for prod

#3775 Update filename tooltip
  public/js/cat_source/es6/components/header/cattol/FilesMenu.js
Labels: Ready for prod

#3777 Improve url replace in segment notes
  public/js/cat_source/es6/utils/textUtils.js
Labels: Ready for prod

#3788 Eq wc null
  lib/Utils/Analysis/Workers/FastAnalysis.php
  lib/Utils/Analysis/Workers/TMAnalysisWorker.php
Labels: Ready for prod

#3787 Change the order of the project creation fields
  public/js/cat_source/es6/components/settingsPanel/ProjectTemplate/TemplateSelect.js
  public/js/cat_source/es6/pages/NewProject.js
Labels: Ready for prod

#3786 Fix for Google Translate
  lib/Controller/engineController.php
  lib/Utils/Engines/GoogleTranslate.php
Labels: Ready for prod

#3763 Fix update of `last_update` field
  lib/Controller/updateJobKeysController.php
  lib/Model/Jobs/JobDao.php
  lib/Utils/ProjectManager.php
  lib/Utils/TmKeyManagement/TmKeyManagement.php
Labels: Ready for prod

#3760 Fix korean inserts when show whitespace chars is active
  public/js/cat_source/es6/components/segments/Editarea.js
Labels: Ready for prod

#3736 Offline management
  public/css/sass/style.scss
  public/js/cat_source/es6/actions/SegmentActions.js
  public/js/cat_source/es6/components/segments/SegmentButtons.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabAiAssistant.js
  public/js/cat_source/es6/components/segments/SegmentFooterTabConcordance.js
  public/js/cat_source/es6/components/segments/SegmentTarget.js
  public/js/cat_source/es6/components/segments/utils/translationMatches.js
  public/js/cat_source/es6/hooks/useAuth.js
  public/js/cat_source/es6/hooks/useSocketLayer.js
  public/js/cat_source/es6/pages/CatTool.js
  public/js/cat_source/es6/sse/SocketListener.js
  public/js/cat_source/es6/utils/offlineUtils.js
  public/js/cat_source/ui.core.js
Labels: Freddy
